CREATE TABLE EMP_MASTER(EMP_CODE VARCHAR2(5) PRIMARY KEY,EMP_NAME VARCHAR2(50),EMP_BIRTH DATE);

CREATE TABLE DEPT_MASTER(DEPT_CODE VARCHAR2(5) PRIMARY KEY,DEPT_NAME VARCHAR2(50),BUDGET NUMBER(10));

CREATE TABLE SALARY(EMP_CODE VARCHAR2(5) REFERENCES EMP_MASTER(EMP_CODE),DEPT_CODE VARCHAR2(5) REFERENCES DEPT_MASTER(DEPT_CODE),SALARY NUMBER(10));

INSERT INTO EMP_MASTER VALUES('E101','MAHESH','28-FEB-2004');
INSERT INTO EMP_MASTER VALUES('E102','KRISHHH','29-FEB-2004');
INSERT INTO EMP_MASTER VALUES('E103','DHRUVVV','8-MAY-2004');

INSERT INTO DEPT_MASTER VALUES('D101','SALES',1000000);
INSERT INTO DEPT_MASTER VALUES('D102','MARKETING',2000000);
INSERT INTO DEPT_MASTER VALUES('D103','HR',500000);

INSERT INTO SALARY VALUES('E101','D101',25000);
INSERT INTO SALARY VALUES('E102','D102',35000);
INSERT INTO SALARY VALUES('E103','D103',55000);


-- FUNCTION --
CREATE OR REPLACE FUNCTION N_S(ENAME VARCHAR2)
RETURN NUMBER
IS
SAL NUMBER;
BEGIN
SELECT SALARY.SALARY INTO SAL FROM SALARY,EMP_MASTER WHERE EMP_NAME IN(SELECT EMP_NAME FROM EMP_MASTER WHERE EMP_NAME=ENAME) AND EMP_MASTER.EMP_CODE = SALARY.EMP_CODE;
RETURN SAL;
EXCEPTION 
WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE('NO DATA FOUND FOR ENTERED EMPLOYEE!!');
END;
/

DECLARE
ENAME VARCHAR2(50);
RESULTT NUMBER;
BEGIN
RESULTT:=N_S('&ENAME');
IF RESULTT IS NOT NULL THEN
DBMS_OUTPUT.PUT_LINE('SALARY FOR ENTERED EMPLOYEE IS: '||RESULTT);
ELSE
DBMS_OUTPUT.PUT_LINE('NO SALARY FOUND FOR ENTERED EMPLOYEE!!');
END IF;
END;
/

-- SELECT SALARY.SALARY FROM SALARY,EMP_MASTER WHERE EMP_NAME IN(SELECT EMP_NAME FROM EMP_MASTER WHERE EMP_NAME='MAHESH') AND EMP_MASTER.EMP_CODE = SALARY.EMP_CODE;


CREATE OR REPLACE TRIGGER ESAL
BEFORE UPDATE ON SALARY
FOR EACH ROW
BEGIN
IF :NEW.SALARY < 0 THEN
RAISE_APPLICATION_ERROR(-20001,'ENTER VALID SALARY');
ELSE
DBMS_OUTPUT.PUT_LINE('UPDATED ');
END IF;
END;
/