-- DAY 17 12-10-2023

-- CREATING TABLES

-- STUDENT TABLE
CREATE TABLE STUDENT(SID NUMBER(10) PRIMARY KEY,SNAME VARCHAR2(50),ADDRESS VARCHAR2(100),DOB DATE);

-- QUESTION TABLE
CREATE TABLE QUESTION(QUESTION_NO NUMBER(10) PRIMARY KEY,QUESTION_TEXT VARCHAR2(100),WEIGHTAGE NUMBER(10));

-- PAPER TABLE
CREATE TABLE PAPER(PAPER_ID NUMBER(10) PRIMARY KEY,SUB_NAME VARCHAR2(50),SEMESTER NUMBER(3),STREAM VARCHAR2(50));

-- EXAM TABLE
CREATE TABLE EXAM(EXAM_ID NUMBER(10) PRIMARY KEY,SID NUMBER(10) REFERENCES STUDENT(SID),PAPER_ID NUMBER(10) REFERENCES PAPER(PAPER_ID),QUESTION_NO NUMBER(10) REFERENCES QUESTION(QUESTION_NO),EXAM_DATE DATE,MARK NUMBER(10));

-- INSERTING 5 RECORDS IN ALL TABLES

-- STUDENT TABLE
INSERT INTO STUDENT VALUES(101,'ALMAS','AHMEDABAD','8-OCT-2004');
INSERT INTO STUDENT VALUES(102,'HARSH','SANAND','10-NOV-2004');
INSERT INTO STUDENT VALUES(103,'NIHAR','PG','12-DEC-2004');
INSERT INTO STUDENT VALUES(104,'WASIM','ISANPUR','14-JAN-2004');
INSERT INTO STUDENT VALUES(105,'BURHAN','AHMEDABAD','16-FEB-2004');

-- QUESTION TABLE
INSERT INTO QUESTION VALUES(01,'WHAT IS HTML?',5);
INSERT INTO QUESTION VALUES(02,'WHAT IS JAVA?',5);
INSERT INTO QUESTION VALUES(03,'WHAT IS C?',5);
INSERT INTO QUESTION VALUES(04,'WHAT IS C++?',5);
INSERT INTO QUESTION VALUES(05,'WHAT IS JAVASCRIPT?',5);
INSERT INTO QUESTION VALUES(06,'WHAT IS SQL?',5);
INSERT INTO QUESTION VALUES(07,'WHAT IS INTERNET?',5);
INSERT INTO QUESTION VALUES(08,'WHAT IS CPU?',5);
INSERT INTO QUESTION VALUES(09,'WHAT IS DBMS?',5);
INSERT INTO QUESTION VALUES(10,'WHAT IS CSS?',5);
INSERT INTO QUESTION VALUES(11,'WHAT IS WOODPECKER?',5);
INSERT INTO QUESTION VALUES(12,'WHAT IS LIGMA?',5);
INSERT INTO QUESTION VALUES(13,'WHAT IS SIGMA?',5);
INSERT INTO QUESTION VALUES(14,'WHO IS ELVISH BHAIIIII?',5);
INSERT INTO QUESTION VALUES(15,'WHAT IS KRISH?',5);

-- PAPER TABLE
INSERT INTO PAPER VALUES(1001,'WDT',1,'BCA');
INSERT INTO PAPER VALUES(1002,'OOPJ',3,'BCA');
INSERT INTO PAPER VALUES(1003,'C',1,'BCA');
INSERT INTO PAPER VALUES(1004,'DBMS',2,'BCA');
INSERT INTO PAPER VALUES(1005,'FCO',1,'BCA');

-- EXAM TABLE
INSERT INTO EXAM VALUES(111,101,1001,01,'20-SEP-2023',80);
INSERT INTO EXAM VALUES(112,101,1001,02,'20-SEP-2023',70);
INSERT INTO EXAM VALUES(113,102,1002,03,'20-SEP-2023',60);
INSERT INTO EXAM VALUES(114,102,1002,04,'20-SEP-2023',50);
INSERT INTO EXAM VALUES(115,103,1003,05,'20-SEP-2023',60);
INSERT INTO EXAM VALUES(116,103,1003,06,'20-SEP-2023',40);
INSERT INTO EXAM VALUES(117,104,1004,07,'20-SEP-2023',70);
INSERT INTO EXAM VALUES(118,104,1004,08,'20-SEP-2023',90);
INSERT INTO EXAM VALUES(119,105,1005,09,'20-SEP-2023',60);
INSERT INTO EXAM VALUES(120,105,1005,10,'20-SEP-2023',40);

-- 1.Using parameterized cursor fetch the details of the students with Exam.Ask Exam Id and Paper Id from User.

DECLARE
ID STUDENT.SID%TYPE;
NAME STUDENT.SNAME%TYPE;
TEST EXAM.EXAM_DATE%TYPE;
EID EXAM.EXAM_ID%TYPE;
PID PAPER.PAPER_ID%TYPE;
CURSOR S1(EEID NUMBER,PPID NUMBER) IS SELECT STUDENT.SID,STUDENT.SNAME,EXAM.EXAM_DATE FROM STUDENT,PAPER,EXAM WHERE STUDENT.SID = EXAM.SID AND PAPER.PAPER_ID = EXAM.PAPER_ID AND PAPER.PAPER_ID=PID AND EXAM.EXAM_ID=EID;
BEGIN
EID:=&EID;
PID:=&PID;
OPEN S1(EID,PID);
LOOP
FETCH S1 INTO ID,NAME,TEST;
EXIT WHEN S1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('STUDENT ID: '||ID||CHR(10)||'STUDENT NAME: '||NAME||CHR(10)||'EXAM DATE: '||TEST);
END LOOP;
CLOSE S1;
END;
/

-- 2.Using Explicit cursor update the exam date where paper id is 1002.

DECLARE
EDATE EXAM.EXAM_DATE%TYPE;
CURSOR S2 IS SELECT EXAM_DATE FROM EXAM WHERE PAPER_ID=1002;
BEGIN
OPEN S2;
LOOP
FETCH S2 INTO EDATE;
UPDATE EXAM SET EXAM_DATE='10-NOV-2023' WHERE PAPER_ID=1002;
DBMS_OUTPUT.PUT_LINE('');
END LOOP;
DBMS_OUTPUT.PUT_LINE('EXAM DATE BEFORE UPDATE: '||EDATE||CHR(10));
CLOSE S2;
END;
/

-- 3.Create a PL/SQL program that uses an explicit cursor to calculate the total number of questions paper wise. 

DECLARE
TOTAL NUMBER;
PID EXAM.PAPER_ID%TYPE;
CURSOR S3 IS SELECT COUNT(QUESTION_NO),PAPER_ID FROM EXAM GROUP BY PAPER_ID;
BEGIN
OPEN S3;
LOOP
FETCH S3 INTO TOTAL,PID;
EXIT WHEN S3%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('PAPER ID: '||PID||CHR(10)||'NO OF QUESTIONS: '||TOTAL);
END LOOP;
CLOSE S3;
END;
/

-- 4. Design a PL/SQL program that uses an explicit cursor to find and display the questions that have not been assigned to any students in a specific paper.

DECLARE
QSTN QUESTION.QUESTION_TEXT%TYPE;
CURSOR S4 IS SELECT QUESTION_TEXT FROM QUESTION WHERE QUESTION_NO NOT IN(SELECT QUESTION_NO FROM EXAM);
BEGIN
OPEN S4;
DBMS_OUTPUT.PUT_LINE('QUESTIONS NOT IN ANY PAPER: '||CHR(10));
LOOP
FETCH S4 INTO QSTN;
EXIT WHEN S4%NOTFOUND;
DBMS_OUTPUT.PUT_LINE(QSTN||CHR(10));
END LOOP;
CLOSE S4;
END;
/

-- 5. Design a PL/SQL program that uses an explicit cursor to update the marks of all students who scored below a certain threshold.

DECLARE

BEGIN
END;
/