/* DAY - 3 22nd September 2023 */

/* FIRST TABLE */
CREATE TABLE LJKU_DEPT(DEPT_NO NUMBER(3) PRIMARY KEY,DEPT_NAME VARCHAR2(35) CHECK (DEPT_NAME IN('MBA','MCA','MscIT','BEIT','CEIT')),LOCATION VARCHAR2(35));

/* SECOND TABLE */
CREATE TABLE FACULTY(FAC_ID NUMBER(3) PRIMARY KEY,FAC_NAME VARCHAR2(35),AGE NUMBER(3) CHECK (AGE >18),GENDER VARCHAR(6),DEPT_NO NUMBER(3) REFERENCES LJKU_DEPT(DEPT_NO),ADDRESS VARCHAR2(100),DESIGNATION VARCHAR2(35),SALARY NUMBER(10) CHECK (SALARY > 0),EXPERIENCE NUMBER(3),EMAIL VARCHAR2(50) CHECK (EMAIL LIKE '%__@_%.__%'));

/* THIRD TABLE */
CREATE TABLE CLASS(CLASS_ID NUMBER(3),CLASSNAME VARCHAR2(35),FAC_ID NUMBER(3) REFERENCES FACULTY(FAC_ID),DEPT_ID NUMBER(3) REFERENCES LJKU_DEPT(DEPT_NO),SUBJECT_TAKEN VARCHAR2(35));

/* QUESTION 1 ADDING MALE FEMALE CONSTRAINTS IN GENDER */
ALTER TABLE FACULTY MODIFY(GENDER VARCHAR(6) CHECK(GENDER IN('MALE','FEMALE')));

/* QUESTION 2 */ /* INCOMPLETE */
/* FIRST ADDING A ROW WITH SUBJECT ='FY' */
INSERT INTO FACULTY VALUES(112,'MAHESH',28,'MALE',101,'AHMEDABAD','PROF',25000,3,'MAHESH@GMAIL.COM');

INSERT INTO CLASS VALUES(121,'FY CLASS',112,101,'FY');

/* DELETING THE ABOVE INSERTED ROW */

DELETE CLASS WHERE SUBJECT_TAKEN='FY' AND FAC_ID IN(SELECT FAC_ID FROM FACULTY);

DELETE FACULTY WHERE FAC_ID IN(SELECT FAC_ID FROM CLASS WHERE SUBJECT_TAKEN='FY');

/* QUESTION - 3  INCOMPLETE*/
/* FIRST ADDING SOME FACULTY IN MCA DEPT */
INSERT INTO FACULTY VALUES(113,'KAMIYA',28,'FEMALE',101,'AHMEDABAD','PROF',35000,5,'KAMIYA@GMAIL.COM');
INSERT INTO FACULTY VALUES(114,'HARSH',19,'MALE',101,'AHMEDABAD','ASS-PROF',35000,5,'HARSH@GMAIL.COM');
INSERT INTO FACULTY VALUES(115,'KRISH',19,'MALE',101,'NALASOPARA','PROF',30000,5,'KRISH@GMAIL.COM');
INSERT INTO FACULTY VALUES(116,'BURHAN',20,'MALE',101,'AHMEDABAD','LAB TECH',35000,5,'BURHAN@GMAIL.COM');
INSERT INTO FACULTY VALUES(117,'DHRUV',19,'MALE',101,'AHMEDABAD','ASS-PROF',30000,5,'DHRUV@GMAIL.COM');

/* COUNTING FACULTIES ACC TO DEPT */

/*SELECT COUNT(FAC_ID) FROM FACULTY GROUP BY DEPT_NAME WHERE DEPT_NO IN(SELECT DEPT_NO FROM LJKU_DEPT);*/

SELECT COUNT(FAC_ID),DEPT_ID FROM CLASS GROUP BY DEPT_ID;
/* QUESTION - 4 */

SELECT FAC_NAME FROM FACULTY WHERE FAC_NAME LIKE('A%_%A');

/* QUESTION - 5 */
/* INCREASING 10% SALARY OF CEIT DEPTS */

UPDATE FACULTY SET SALARY=SALARY + (SALARY)*0.1 WHERE DEPT_NO IN(SELECT DEPT_NO FROM LJKU_DEPT WHERE DEPT_NAME='CEIT');

/* QUESTION - 6 */

SELECT FAC_NAME,SALARY FROM FACULTY WHERE SALARY IN(SELECT MIN(SALARY) FROM FACULTY);

/* QUESTION 7 */ /* INCOMPLETE */

SELECT FACULTY.FAC_NAME,LJKU_DEPT.DEPT_NAME FROM FACULTY,LJKU_DEPT AS 'FACULTY WORKING IN DEPARTMENT MCA' WHERE LJKU_DEPT.DEPT_NO = FACULTY.DEPT_NO AND LJKU.DEPT_NO IN(101);

/* QUESTION 8 */ /* INCOMPLETE */

SELECT FACULTY.FAC_NAME,LJKU_DEPT.DEPT_NAME FROM FACULTY,LJKU_DEPT GROUP BY LJKU_DEPT.DEPT_NAME WHERE FACULTY.DEPT_NO = LJKU_DEPT_NO AND FACULTY.EXPERIENCE > 5);

/* QUESTION 9 */

SELECT DEPT_NAME FROM LJKU_DEPT WHERE DEPT_NO NOT IN(SELECT DEPT_NO FROM FACULTY);

/* ROUGH QUERIES */
INSERT INTO LJKU_DEPT VALUES(101,'MCA','AHMEDABAD');
INSERT INTO LJKU_DEPT VALUES(103,'MscIT','AHMEDABAD');
INSERT INTO LJKU_DEPT VALUES(104,'BEIT','AHMEDABAD');
INSERT INTO FACULTY VALUES(111,'MAMAD SIR',19,'MALE',101,'AHMEDABAD','PROF',50000,15,'MAMAD@GMAIL.COM');
INSERT INTO FACULTY VALUES(118,'ADITYA',19,'MALE',101,'AHMEDABAD','ASS-PROF',32000,1,'ADITYA@GMAIL.COM');
INSERT INTO FACULTY VALUES(119,'ASHA',20,'FEMALE',101,'AHMEDABAD','PROF',50000,2,'ASHA@GMAIL.COM');
INSERT INTO LJKU_DEPT VALUES(102,'CEIT','SARKHEJ');
INSERT INTO FACULTY VALUES(121,'GANESH',20,'MALE',102,'SANAND','ASS-PROF',45000,2,'GANESH@GMAIL.COM');

/* PRACTICE */

SELECT LJKU_DEPT.DEPT_NAME,FACULTY.FAC_NAME,CLASS.CLASSNAME FROM LJKU_DEPT,FACULTY,CLASS WHERE LJKU_DEPT.DEPT_NO = FACULTY.DEPT_NO AND FACULTY.FAC_ID = CLASS.FAC_ID;

SELECT FACULTY.FAC_NAME,CLASS.CLASSNAME,CLASS.SUBJECT_TAKEN FROM FACULTY,CLASS WHERE FACULTY.FAC_ID = CLASS.FAC_ID AND FACULTY.FAC_NAME IN('KAMIYA');

SELECT FACULTY.FAC_NAME,CLASS.CLASSNAME FROM FACULTY,CLASS WHERE FACULTY.FAC_ID = CLASS.FAC_ID AND CLASS.CLASSNAME NOT IN('SECOND YEAR');
/* INSERTING VALUES IN CLASS TABLE */
INSERT INTO CLASS VALUES(131,'DIV C',113,101,'PLSQL');
INSERT INTO CLASS VALUES(132,'SECOND YEAR',116,101,'OOPJ');
INSERT INTO CLASS VALUES(133,'SECOND YEAR',117,101,'ADV C');

INSERT INTO FACULTY VALUES(123,'ROHAN',39,'MALE',103,'VISHALA','PROF',55000,10,'ROHAN@GMAIL.COM');

