-- DAY 6 27TH SEPT 2023
-- CREATING TABLES
CREATE TABLE SAILORS(SID NUMBER(5) PRIMARY KEY,SNAME VARCHAR2(50),RATING NUMBER(2) CHECK RATING IN(1,2,3,4,5,6,7,8,9,10),AGE NUMBER(2));
CREATE TABLE BOATS(BID NUMBER(5) PRIMARY KEY,BNAME VARCHAR2(50),COLOR VARCHAR2(50));
CREATE TABLE RESERVES(SID NUMBER(5) REFERENCES SAILORS(SID),BID NUMBER(5) REFERENCES BOATS(BID),DAY DATE);

-- INSERTING 5 RECORDS IN EACH TABLE
-- SAILORS TABLE
INSERT INTO SAILORS VALUES(101,'CAPTAIN JACK',9,38);
INSERT INTO SAILORS VALUES(102,'CAPTAIN JOHN',8,28);
INSERT INTO SAILORS VALUES(103,'CAPTAIN WILL',6,23);
INSERT INTO SAILORS VALUES(104,'CAPTAIN BILL',5,33);
INSERT INTO SAILORS VALUES(105,'CAPTAIN MINDI',4,20);

-- BOATS TABLE
INSERT INTO BOATS VALUES(201,'FRIGATE','BROWN');
INSERT INTO BOATS VALUES(202,'MERCHANTMAN','BLACK');
INSERT INTO BOATS VALUES(203,'SLOOP','LIGHT BROWN');
INSERT INTO BOATS VALUES(204,'PINNACE','GREEN');
INSERT INTO BOATS VALUES(205,'RAFT','GRAY');

-- RESERVES TABLE
INSERT INTO RESERVES VALUES(101,201,);