/*  DAY - 4 */

/* SQL BLOCK */
DECLARE
SNO STUDENT.ROLLNO%TYPE;
SFNAME STUDENT.FNAME%TYPE;
SDOB STUDENT.DOB%TYPE;
BEGIN
SELECT ROLLNO,FNAME,DOB INTO SNO,SFNAME,SDOB FROM STUDENT WHERE FNAME='ALMAS';
DBMS_OUTPUT.PUT_LINE('STUDENT ROLLNO: '||SNO||' '||'STUDENT FIRSTNAME: '||SFNAME||' '||' STUDENT DOB: '||SDOB);
END;
-- COMMENT 

-- SCHEDULE DAY 7  ESSENTIAL QUESTION 1

-- CREATING TABLE

CREATE TABLE EMPLOYEE(EID NUMBER(4),ENAME VARCHAR2(50),DEPT VARCHAR2(50),JOB VARCHAR2(50),SALARY NUMBER(10));

-- INSERTING VALUES

INSERT INTO EMPLOYEE VALUES(101,'MAHESH','10','CLERK',1700);
INSERT INTO EMPLOYEE VALUES(102,'MUKESH','21','MANAGER',5000);
INSERT INTO EMPLOYEE VALUES(103,'RAMESH','22','ASSISTANT MANAGER',7500);
INSERT INTO EMPLOYEE VALUES(104,'GANESH','25','SALESMAN',9500);
INSERT INTO EMPLOYEE VALUES(105,'DIKESH','26','BOSS',17500);
INSERT INTO EMPLOYEE VALUES(106,'BURHAN','27','MANAGER',5000);

-- WRITING SQL BLOCK
-- F I R S T QUERY


DECLARE
E_NAME EMPLOYEE.ENAME%TYPE;
E_JOB EMPLOYEE.JOB%TYPE;
BEGIN
SELECT ENAME,JOB INTO E_NAME,E_JOB FROM EMPLOYEE WHERE JOB='CLERK' AND SALARY=1700;
DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME: '||E_NAME||' JOB: '||E_JOB);
END;


-- S E C O N D QUERY


DECLARE
M_COUNT EMPLOYEE.EID%TYPE;
BEGIN
SELECT COUNT(JOB) INTO M_COUNT FROM EMPLOYEE WHERE JOB IN('MANAGER');
DBMS_OUTPUT.PUT_LINE('NO OF MANAGERS: '||M_COUNT);
END;


-- T H I R D QUERY


DECLARE
TOTAL EMPLOYEE.SALARY%TYPE;
BEGIN
SELECT SUM(SALARY) INTO TOTAL FROM EMPLOYEE;
DBMS_OUTPUT.PUT_LINE('TOTAL SALARY: '||TOTAL);
END;


