-- EXCERCISE FOR DAY 24 21ST-OCT-2023 --
-- TABLES REQUIRED --

-- DISTRIBUTOR TABLE --
CREATE TABLE DISTRIBUTOR(DNO NUMBER(10) PRIMARY KEY, DNAME VARCHAR2(50), DADDRESS VARCHAR2(50), DPHONE NUMBER(10));

INSERT INTO DISTRIBUTOR VALUES(101,'DEV','AHMEDABAD',6969696969);
INSERT INTO DISTRIBUTOR VALUES(102,'ELVISH BHAIIII','MUMBAI',1010101010);
INSERT INTO DISTRIBUTOR VALUES(103,'BURHAN','AHMEDABAD',2020202020);
INSERT INTO DISTRIBUTOR VALUES(104,'KRISH','PRAHLADNAGAR',3030303030);
INSERT INTO DISTRIBUTOR VALUES(105,'VIKAS','NURSERY',4040404040);

-- ITEM TABLE --
CREATE TABLE ITEM (ITEMNO NUMBER(10) PRIMARY KEY, ITEM_NAME VARCHAR2(50), COLOUR VARCHAR2(50), WEIGHT NUMBER(10));

INSERT INTO ITEM VALUES(111,'GLASSES','VARIOUS',100);
INSERT INTO ITEM VALUES(112,'TOYS','VARIOUS',100);
INSERT INTO ITEM VALUES(113,'BEVERAGES','VARIOUS',100);
INSERT INTO ITEM VALUES(114,'GROCERY','VARIOUS',100);
INSERT INTO ITEM VALUES(115,'PERFUMES','VARIOUS',100);

-- DIST_ITEM TABLE --
CREATE TABLE DIST_ITEM (DNO NUMBER(10) REFERENCES DISTRIBUTOR(DNO), ITEMNO NUMBER(10) REFERENCES ITEM(ITEMNO), QTY NUMBER(10));

INSERT INTO DIST_ITEM VALUES(101,111,10);
INSERT INTO DIST_ITEM VALUES(102,112,20);
INSERT INTO DIST_ITEM VALUES(103,113,30);
INSERT INTO DIST_ITEM VALUES(104,114,40);
INSERT INTO DIST_ITEM VALUES(105,115,50);


-- Q. 1 Write a pl/sql block to call a procedure that counts total items supplied by each distributor and display them. Also write a function that asks for item name and displays its weight.

-- A -- PROCEDURE FOR Q1
CREATE OR REPLACE PROCEDURE CNTITEM(DID IN NUMBER,DIDD OUT NUMBER,CNT OUT NUMBER)
IS
BEGIN
SELECT DNO,COUNT(QTY) INTO DIDD,CNT FROM DIST_ITEM GROUP BY DNO HAVING DNO=DID;
END;
/

-- CALLING ABOVE PROCEDURE --
DECLARE
DID NUMBER;
DIDD NUMBER;
CNT NUMBER;
BEGIN
CNTITEM(&DID,DIDD,CNT);
DBMS_OUTPUT.PUT_LINE('DISTRIBUTOR ID: '||DIDD||CHR(10)||'NO OF ITEMS: '||CNT);
END;
/

-- FUNCTION FOR Q1 -- 
-- INCOMPLETE --

CREATE OR REPLACE FUNCTION DISPWEIGH(INAME VARCHAR)
RETURN NUMBER
IS
WEI NUMBER;
BEGIN
SELECT WEIGHT INTO WEI FROM ITEM WHERE ITEM_NAME=INAME;
RETURN WEI;
END;
/

DECLARE
WW NUMBER;
INAME VARCHAR2(50);
BEGIN
WW:=DISPWEIGH('&INAME');
DBMS_OUTPUT.PUT_LINE('WEIGHT OF '||INAME||' IS: '||WW);
END;
/