-- DAY 9 
-- BLOCK EXCERCISE WITH PROMPT VALUE
-- CREATING TABLES

-- TABLE 1 SUPPLIER
CREATE TABLE SUPPLIER(SID NUMBER(5) PRIMARY KEY,SNAME VARCHAR2(50),CONTACT NUMBER(10));
-- TABLE 2 PARTS
CREATE TABLE PARTS(PID NUMBER(5) PRIMARY KEY,PNAME VARCHAR2(50),COLOR VARCHAR2(25),PRICE NUMBER(6));
-- TABLE 3 CATALOG
CREATE TABLE CATALOG(SID NUMBER(5) REFERENCES SUPPLIER(SID),PID NUMBER(5) REFERENCES PARTS(PID),QTY NUMBER(5));

-- INSERTING RECORDS IN SUPPLIER TABLE
INSERT INTO SUPPLIER VALUES(101,'TOMMY',9898767622);
INSERT INTO SUPPLIER VALUES(102,'TREVOR',6787567677);
INSERT INTO SUPPLIER VALUES(103,'TONI',1212343456);
INSERT INTO SUPPLIER VALUES(104,'CJ',5656454523);
INSERT INTO SUPPLIER VALUES(105,'FRANKLIN',7878676790);
INSERT INTO SUPPLIER VALUES(106,'MICHAEL',8899565643);

-- INSERTING RECORDS IN PARTS TABLE
INSERT INTO PARTS VALUES(111,'SCREEN','NULL',1500);
INSERT INTO PARTS VALUES(112,'BATTERY','GREY',2000);
INSERT INTO PARTS VALUES(113,'CASE','VARIOUS',500);
INSERT INTO PARTS VALUES(114,'STYLUS','VARIOUS',1200);
INSERT INTO PARTS VALUES(115,'CAMERA','BLACK',2500);

-- INSERTING VALUES IN CATALOG TABLE
INSERT INTO CATALOG VALUES(101,111,5);
INSERT INTO CATALOG VALUES(101,112,5);
INSERT INTO CATALOG VALUES(102,112,5);
INSERT INTO CATALOG VALUES(103,113,5);
INSERT INTO CATALOG VALUES(104,114,5);
INSERT INTO CATALOG VALUES(105,115,5);

-- QUESTION 1
DECLARE
SID1 SUPPLIER.SID%TYPE;
SNAME1 SUPPLIER.SNAME%TYPE;
CONTACT1 SUPPLIER.CONTACT%TYPE;
PID1 PARTS.PID%TYPE;
PNAME1 PARTS.PNAME%TYPE;
PRICE1 PARTS.PRICE%TYPE;
BEGIN
SID1:=&SID1;
SELECT SUPPLIER.SNAME,SUPPLIER.CONTACT,PARTS.PID,PARTS.PNAME,PARTS.PRICE INTO SNAME1,CONTACT1,PID1,PNAME1,PRICE1 FROM SUPPLIER,PARTS,CATALOG WHERE SUPPLIER.SID = CATALOG.SID AND PARTS.PID = CATALOG.PID AND SUPPLIER.SID = SID1; 
DBMS_OUTPUT.PUT_LINE('SUPPLIER NAME: '||SNAME1||' SUPPLIER CONTACT: '||CONTACT1||' PART ID: '||PID1||' PART NAME: '||PNAME1||' PART PRICE: '||PRICE1);
END;
/
-- QUESTION 2
DECLARE
PNO PARTS.PID%TYPE;
PNAME1 PARTS.PNAME%TYPE;
COLOR1 PARTS.COLOR%TYPE;
PRICE1 PARTS.PRICE%TYPE;
BEGIN
PNAME1:='&PNAME1';
SELECT PID,PNAME,COLOR,PRICE INTO PNO,PNAME1,COLOR1,PRICE1 FROM PARTS WHERE PNAME=PNAME1;
DBMS_OUTPUT.PUT_LINE('DETAILS FOR ENTERED PNAME ARE: ');
DBMS_OUTPUT.PUT_LINE('PNAME: '||PNAME1||' PNO: '||PNO||' COLOR: '||COLOR1||' PRICE: '||PRICE1);
END;
/
-- QUESTION 3 
DECLARE
SNO SUPPLIER.SID%TYPE;
SNAME1 SUPPLIER.SNAME%TYPE;
SCONTACT SUPPLIER.CONTACT%TYPE;
BEGIN
SELECT SUPPLIER.SID,SUPPLIER.SNAME,SUPPLIER.CONTACT INTO SNO,SNAME1,SCONTACT FROM SUPPLIER WHERE SID NOT IN(SELECT SID FROM CATALOG);
DBMS_OUTPUT.PUT_LINE('SUPPLIER WHO HAS NOT ORDERED ANY PARTS: ');
DBMS_OUTPUT.PUT_LINE('NAME: '||SNAME1||' ID: '||SNO||' CONTACT: '||SCONTACT);
END;
/
-- QUESTION 4 
DECLARE
SNO SUPPLIER.SID%TYPE;
SNAME1 SUPPLIER.SNAME%TYPE;
SCONTACT SUPPLIER.CONTACT%TYPE;
BEGIN
SELECT SUPPLIER.SID,SUPPLIER.SNAME,SUPPLIER.CONTACT INTO SNO,SNAME1,SCONTACT FROM SUPPLIER,PARTS,CATALOG WHERE SUPPLIER.SID = CATALOG.SID AND PARTS.PID = CATALOG.PID AND PARTS.PRICE > 500;
DBMS_OUTPUT.PUT_LINE(' ID: '||SNO||' NAME: '||SNAME1||' CONTACT: '||SCONTACT);
EXCEPTION
WHEN TOO_MANY_ROWS THEN
DBMS_OUTPUT.PUT_LINE('THERE ARE MORE THAN ONE ROWS OF THIS QUERY!!');
END;
/
-- QUESTION 5
DECLARE
DPRICE PARTS.PRICE%TYPE;
SNO SUPPLIER.SID%TYPE;
BEGIN
END;
/

-- QUESTION6 INCOMPLETE!!!
DECLARE
COUNT1 CATALOG.QTY%TYPE;
SNO SUPPLIER.SID%TYPE;
BEGIN
SNO:=&SNO;
SELECT COUNT(PID),SID INTO COUNT1,SNO FROM CATALOG WHERE SID=SNO GROUP BY SID;
DBMS_OUTPUT.PUT_LINE('NAME: '||SNO||' PARTS PURCHASED: '||COUNT1);
END;
/