-- DAY - 6 
-- CREATING TABLES
CREATE TABLE EMP(EMP_NO VARCHAR(10),EMP_NAME VARCHAR2(25),EMP_ADDRESS VARCHAR2(100),EMP_PHNO NUMBER(10),DEPT_NO VARCHAR2(25),DEPT_NAME VARCHAR2(25),JOB_ID VARCHAR2(10),SALARY NUMBER(10));

-- INSERTING VALUES
INSERT INTO EMP VALUES('E1001','MAHESH','MAHESH NAGAR',9898767654,'D101','MARKETING','J101',25000);
INSERT INTO EMP VALUES('E1002','RAMESH','RAMESH NAGAR',1234567654,'D102','SALES','J102',15000);
INSERT INTO EMP VALUES('E1003','ADITYA','ADITYA NAGAR',1212121212,'D103','SERVICE','J103',35000);
INSERT INTO EMP VALUES('E1004','TOMMY','VICE CITY',7898547362,'D104','FINANCE','J104',55000);
INSERT INTO EMP VALUES('E1005','MOHIT','NARODA',6756535453,'D105','MANAGEMENT','J105',22500);
INSERT INTO EMP VALUES('E1006','ROHIT','SARKHEJ',5634728432,'D10','MANAGEMENT','J106',22500);
INSERT INTO EMP VALUES('E1012','RAHUL','SARKHEJ',26829533,'D12','MANAGEMENT','J107',22500);
INSERT INTO EMP VALUES('E1013','TREVOR','BLAINE COUNTY',4567839222,'D11','MECH','J108',45000);
INSERT INTO EMP VALUES('E1014','CJ','LOS SANTOS',9944553324,'D13','IT PROF','J109',75000);
INSERT INTO EMP VALUES('E1015','MICHAEL DE SANTA','LOS SANTOS',4677754343,'D14','FINANCE','J110',76000);

-- QUESTION - 1
DECLARE
ENAME EMP.EMP_NAME%TYPE;
BEGIN
SELECT EMP_NAME INTO ENAME FROM EMP WHERE EMP_NAME LIKE('%A');
DBMS_OUTPUT.PUT_LINE('EMPLOYEE WITH NAME ENDING WITH "A": '||ENAME);
END;
/
-- QUESTION 2
BEGIN
INSERT INTO EMP VALUES('E1007','JOHN','DELHI',9887655432,'E1007','SALES','J1007',30000);
DBMS_OUTPUT.PUT_LINE('ROW INSERTED!');
END;
/
-- QUESTION 3
DECLARE
EID EMP.EMP_NO%TYPE;
NAME EMP.EMP_NAME%TYPE;
EADD EMP.EMP_ADDRESS%TYPE;
EPH EMP.EMP_PHNO%TYPE;
EDEPT EMP.DEPT_NO%TYPE;
EDEPTNAME EMP.DEPT_NAME%TYPE;
EJOB EMP.JOB_ID%TYPE;
ESAL EMP.SALARY%TYPE;
BEGIN
SELECT * INTO EID,NAME,EADD,EPH,EDEPT,EDEPTNAME,EJOB,ESAL FROM EMP WHERE EMP_ADDRESS='NARODA' AND SALARY > 15000;
DBMS_OUTPUT.PUT_LINE('ID: '||EID||' NAME: '||NAME||' ADDRESS: '||EADD||' PHONE NUMBER: '||EPH||' DEPARTMENT NO: '||EDEPT||' DEPARTMENT: '||EDEPTNAME||' JOB ID: '||EJOB||' SALARY: '||ESAL);
END;
/
-- QUESTION 4
DECLARE
EID EMP.EMP_NO%TYPE;
NAME EMP.EMP_NAME%TYPE;
EADD EMP.EMP_ADDRESS%TYPE;
EPH EMP.EMP_PHNO%TYPE;
EDEPT EMP.DEPT_NO%TYPE;
EDEPTNAME EMP.DEPT_NAME%TYPE;
EJOB EMP.JOB_ID%TYPE;
ESAL EMP.SALARY%TYPE;
BEGIN
SELECT * INTO EID,NAME,EADD,EPH,EDEPT,EDEPTNAME,EJOB,ESAL FROM EMP WHERE DEPT_NO='D10';
DBMS_OUTPUT.PUT_LINE('ID: '||EID||' NAME: '||NAME||' ADDRESS: '||EADD||' PHONE NUMBER: '||EPH||' DEPARTMENT NO: '||EDEPT||' DEPARTMENT: '||EDEPTNAME||' JOB ID: '||EJOB||' SALARY: '||ESAL);
END;
/

-- QUESTION 5
BEGIN
UPDATE EMP SET EMP_ADDRESS='NAGPUR' WHERE EMP_NO='E1012';
DBMS_OUTPUT.PUT_LINE('DONE!!!');
END;
/
-- QUESTION 6
DECLARE
ID EMP.EMP_NO%TYPE;
NAME EMP.EMP_NAME%TYPE;
JOB EMP.JOB_ID%TYPE;
DEPT EMP.DEPT_NAME%TYPE;
SALARY EMP.SALARY%TYPE;
BEGIN
SELECT EMP_NO,EMP_NAME,JOB_ID,DEPT_NAME,SALARY INTO ID,NAME,JOB,DEPT,SALARY FROM EMP WHERE DEPT_NAME='MECH';
DBMS_OUTPUT.PUT_LINE('ID: '||ID||' NAME: '||NAME||' JOB: '||JOB||' DEPT: '||DEPT||' SALARY: '||SALARY);
END;
/
-- QUESTION 7
BEGIN
DELETE EMP WHERE JOB_ID='J107';
DBMS_OUTPUT.PUT_LINE('SUCESSFULLY DELETED!!');
END;
/
-- QUESTION 8

-- QUESTION 9
DECLARE
MAXIMUM EMP.SALARY%TYPE;
BEGIN
SELECT MAX(SALARY) INTO MAXIMUM FROM EMP;
DBMS_OUTPUT.PUT_LINE('MAXIMUM SALARY IS: '||MAXIMUM);
END;
/
-- IMPORTANT
-- EXCEPTION HANDLING IN SQL
-- EXAMPLE QUERY
-- EXCEPTION FOR NO DATA FOUND : NO_DATA_FOUND
-- EXCEPTION FOR TOO MANY ROWS: TOO_MANY_ROWS
DECLARE
NAME EMP.EMP_NAME%TYPE;
BEGIN
SELECT EMP_NAME INTO NAME FROM EMP WHERE SALARY>1000000; --NO EMPLOYEE EARNS 1 MILLION SO IT SHOULD THROW AN EXCEPTION
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO DATA FOUND FOR CURRENT CRITERIA!'); --PRINTING CUSTOM ERROR MESSAGE
END;
/
-- QUESTION 10

-- QUESTION 13
DECLARE
EID EMP.EMP_NO%TYPE;
NAME EMP.EMP_NAME%TYPE;
EADD EMP.EMP_ADDRESS%TYPE;
EPH EMP.EMP_PHNO%TYPE;
EDEPT EMP.DEPT_NO%TYPE;
EDEPTNAME EMP.DEPT_NAME%TYPE;
EJOB EMP.JOB_ID%TYPE;
ESAL EMP.SALARY%TYPE;
BEGIN
SELECT * INTO EID,NAME,EADD,EPH,EDEPT,EDEPTNAME,EJOB,ESAL FROM EMP WHERE SALARY > (SELECT SALARY FROM EMP WHERE DEPT_NAME='IT PROF');
DBMS_OUTPUT.PUT_LINE('ID: '||EID||' NAME: '||NAME||' ADDRESS: '||EADD||' PHONE NUMBER: '||EPH||' DEPARTMENT NO: '||EDEPT||' DEPARTMENT: '||EDEPTNAME||' JOB ID: '||EJOB||' SALARY: '||ESAL);
END;
/