-- 25 - 10 - 2023 --
-- EXCERCISE --

-- TABLES REQUIRED --
CREATE TABLE SAILOR(SID NUMBER(10) PRIMARY KEY, SNAME VARCHAR2(50), RATING NUMBER(2) CHECK(RATING IN(0,1,2,3,4,5,6,7,8,9,10)),DOB DATE);

CREATE TABLE BOAT (BID NUMBER(10) PRIMARY KEY, BNAME VARCHAR2(50), COLOR VARCHAR2(50));

CREATE TABLE RESERVE(SID NUMBER(10) REFERENCES SAILOR(SID), BID NUMBER(10) REFERENCES BOAT(BID), RDATE DATE);

-- INSERTING VALUES --

INSERT INTO SAILOR VALUES(101,'BURHAN',8,'17-JUL-2007');
INSERT INTO SAILOR VALUES(102,'HARSH',7,'7-JUN-2007');
INSERT INTO SAILOR VALUES(103,'NIHAR',7,'20-JUN-2007');
INSERT INTO SAILOR VALUES(104,'MAHESH',5,'11-AUG-2007');
INSERT INTO SAILOR VALUES(105,'ELVISH BHAIII',0,'7-SEP-2007');

INSERT INTO BOAT VALUES(111,'SHIPPP','BROWN');
INSERT INTO BOAT VALUES(112,'SHIPPP','BROWN');
INSERT INTO BOAT VALUES(113,'SHIPPP','BROWN');
INSERT INTO BOAT VALUES(114,'TITANIC','SILVER');
INSERT INTO BOAT VALUES(115,'SLOOP','BLACK');

INSERT INTO RESERVE VALUES(101,111,'10-JUL-2023');
INSERT INTO RESERVE VALUES(102,112,'11-JUL-2023');
INSERT INTO RESERVE VALUES(103,113,'12-JUL-2023');
INSERT INTO RESERVE VALUES(104,114,'13-JUL-2023');
INSERT INTO RESERVE VALUES(105,115,'14-JUL-2023');


-- Q. 1 Write a pl/sql block to call a procedure that counts total boats reserved by each sailor and display them. Also write a function that asks for boat id and displays its color.

-- ############################################################### --
CREATE OR REPLACE PROCEDURE CNTBT(ID IN NUMBER,CNT OUT NUMBER)
IS
BEGIN
SELECT COUNT(BID) INTO CNT FROM RESERVE GROUP BY SID;
END;
/

DECLARE
ID NUMBER;
CNT NUMBER;
BEGIN
CNTBT(&ID,CNT);
DBMS_OUTPUT.PUT_LINE('NO OF BOATS RESERVED ARE:'||CNT);
END;
/
-- ############################################################### --
CREATE OR REPLACE FUNCTION B_COLOR(ID NUMBER)
RETURN VARCHAR2
IS
CLR VARCHAR2(50);
BEGIN
SELECT COLOR INTO CLR FROM BOAT WHERE BID=ID;
RETURN CLR;
END;
/

DECLARE
ID NUMBER;
CLR VARCHAR2(50);
BEGIN
CLR := B_COLOR(&ID);
DBMS_OUTPUT.PUT_LINE('cOLOR OF BOAT IS: '||CLR);
END;
/

-- Q. 2 Write and call a parameterized cursor that takes sailor name as an argument and return its age. Throw an exception if no sailor is found.

DECLARE
NAME SAILOR.SNAME%TYPE;
BDAY DATE;
CURSOR S1(NAME IN VARCHAR2) IS SELECT DOB FROM SAILOR WHERE SNAME=NAME;
BEGIN
OPEN S1('&NAME');
FETCH S1 INTO BDAY;
IF S1%NOTFOUND THEN
CLOSE S1;
RAISE_APPLICATION_ERROR(-20001,'NO SAILOR FOUND');
ELSE
DBMS_OUTPUT.PUT_LINE('BIRTHDAY OF ENTERED SAILOR IS: '||BDAY);
END IF;
END;
/