-- DAY 13
-- NEW LOGIN DETAILS FOR SQL PLUS

			-- LOGIN:- IMCAC22008
			-- PASS:- IMCAC22008
			-- HOST STRING:-ORACLE4

-- TABLES REQUIRED FOR THE QUESTIONS

-- EMPLOYEE TABLE

CREATE TABLE EMPLOYEE(EMP_ID NUMBER(10),EMP_NAME VARCHAR2(30),EXPERIENCE NUMBER(3),CITY VARCHAR2(30),SALARY NUMBER(10),MANAGER_ID NUMBER(5) REFERENCES MANAGER(MANAGER_ID));

-- MANAGER TABLE
CREATE TABLE MANAGER(MANAGER_ID NUMBER(5) PRIMARY KEY,MANAGER_NAME VARCHAR2(30));

-- INSERTING RECORDS IN EMPLOYEE TABLE

INSERT INTO EMPLOYEE VALUES(101,'ALMAS BHISTI',4,'AHMEDABAD',30000,1001);
INSERT INTO EMPLOYEE VALUES(102,'SURAJ CHAUHAN',4,'MUMBAI',27500,1002);
INSERT INTO EMPLOYEE VALUES(103,'TREVOR PHILLIPS',4,'RED COUNTY',30000,1003);
INSERT INTO EMPLOYEE VALUES(104,'BURHAN SHAIKH',4,'AHMEDABAD',20000,1004);
INSERT INTO EMPLOYEE VALUES(105,'MAX PAYNE',4,'NEW YORK',24000,1005);
INSERT INTO EMPLOYEE VALUES(106,'JUNED CHAUHAN',3,'AMBER TOWER',22000,1006);
INSERT INTO EMPLOYEE VALUES(107,'ASIF SHAH',2,'FATEHWADI',21000,1006);
INSERT INTO EMPLOYEE VALUES(108,'ELVISHHHH BHAIIII',1,'AHMEDABAD',2000,1006);
INSERT INTO EMPLOYEE VALUES(109,'STEVE',3,'PUNE',20000,1007);
INSERT INTO EMPLOYEE VALUES(110,'BOB',4,'KOLKATA',24000,1007);

-- INSERTING RECORDS IN MANAGER TABLE

INSERT INTO MANAGER VALUES(1001,'TOMMY VERCETTI');
INSERT INTO MANAGER VALUES(1002,'CARL JOHNSON');
INSERT INTO MANAGER VALUES(1003,'HARSHRAJ');
INSERT INTO MANAGER VALUES(1004,'NIHAR');
INSERT INTO MANAGER VALUES(1005,'DHRUV');
INSERT INTO MANAGER VALUES(1006,'SURAJ CHAUHAN');
INSERT INTO MANAGER VALUES(1007,'MANAGER');


-- QUESTIONS

-- 1.	Write a PL/SQL block to calculate and display the employee details with manager.

DECLARE
E_ID EMPLOYEE.EMP_ID%TYPE;
E_NAME EMPLOYEE.EMP_NAME%TYPE;
SAL EMPLOYEE.SALARY%TYPE;
M_ID MANAGER.MANAGER_ID%TYPE;
M_NAME MANAGER.MANAGER_NAME%TYPE;
CURSOR M1 IS SELECT EMPLOYEE.EMP_ID,EMPLOYEE.EMP_NAME,EMPLOYEE.SALARY,MANAGER.MANAGER_ID,MANAGER.MANAGER_NAME FROM EMPLOYEE,MANAGER WHERE MANAGER.MANAGER_ID = EMPLOYEE.MANAGER_ID;
BEGIN
OPEN M1;
LOOP
FETCH M1 INTO E_ID,E_NAME,SAL,M_ID,M_NAME;
EXIT WHEN M1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('EMP_ID: '||E_ID||' EMP NAME: '||E_NAME||' SAL'||SAL||' MANAER_ID: '||M_ID||' MANAGER NAME: '||M_NAME);
END LOOP;
CLOSE M1;
END;
/

-- 2.	Write a PL/SQL block to calculate and display the average salary of all employees.

DECLARE
AVG_SAL EMPLOYEE.SALARY%TYPE;
CURSOR S1 IS SELECT AVG(SALARY) FROM EMPLOYEE;
BEGIN
OPEN S1;
LOOP
FETCH S1 INTO AVG_SAL;
EXIT WHEN S1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('AVERAGE SALARY: '||AVG_SAL);
END LOOP;
CLOSE S1;
END;
/

-- 3.	Write a PL/SQL block to find and display the total number of employee works under ‘suraj chauhan’.

DECLARE
COUNT_EMP NUMBER;
-- ENAME EMPLOYEE.EMP_NAME%TYPE;
CURSOR C1 IS SELECT COUNT(EMP_ID) FROM EMPLOYEE,MANAGER WHERE EMPLOYEE.MANAGER_ID = MANAGER.MANAGER_ID AND MANAGER.MANAGER_NAME='SURAJ CHAUHAN';
BEGIN
OPEN C1;
LOOP
FETCH C1 INTO COUNT_EMP;
EXIT WHEN C1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('NO OF EMPLOYEES WORKING UNDER SURAJ CHAUHAN: '||COUNT_EMP);
END LOOP;
CLOSE C1;
END;
/

-- 4.	Write a PL/SQL block to display the customers who are from ‘Ahmedabad’ City.
DECLARE
EID EMPLOYEE.EMP_ID%TYPE;
ENAME EMPLOYEE.EMP_NAME%TYPE;
CURSOR C2 IS SELECT EMP_ID,EMP_NAME FROM EMPLOYEE WHERE CITY='AHMEDABAD';
BEGIN
OPEN C2;
DBMS_OUTPUT.PUT_LINE('NAME OF PPL FROM AHMEDABAD: ');
LOOP
FETCH C2 INTO EID,ENAME;
EXIT WHEN C2%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('ID: '||EID||' NAME: '||ENAME);
END LOOP;
CLOSE C2;
END;
/

-- 5.	Write a PL/SQL block to find and display the details of customers who works under ‘Manager’.

DECLARE
EID EMPLOYEE.EMP_ID%TYPE;
ENAME EMPLOYEE.EMP_NAME%TYPE;
CURSOR C3 IS SELECT EMP_ID,EMP_NAME FROM EMPLOYEE,MANAGER WHERE EMPLOYEE.MANAGER_ID = MANAGER.MANAGER_ID AND MANAGER_NAME='MANAGER';
BEGIN
DBMS_OUTPUT.PUT_LINE('PPL WORKING UNDER MANAGER: ');
OPEN C3;
LOOP
FETCH C3 INTO EID,ENAME;
EXIT WHEN C3%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('ID: '||EID||CHR(10)||' NAME: '||ENAME);
END LOOP;
CLOSE C3;
END;
/

-- 6.	Write a PL/SQL block to display the manager name and the number of employees in each manager.

DECLARE
M_ MANAGER.MANAGER_NAME%TYPE;
COUNT_EMP NUMBER;
CURSOR C4 IS SELECT COUNT(EMP_ID),MANAGER_ID FROM EMPLOYEE GROUP BY MANAGER_ID; -- GROUP BY MANAGER NAME INCOMPLETE

-- SELECT COUNT(EMP_ID),MANAGER_ID FROM EMPLOYEE GROUP BY MANAGER_ID; -- GROUP BY MANAGER NAME INCOMPLETE

BEGIN
OPEN C4;
LOOP
FETCH C4 INTO COUNT_EMP,M_ID;
EXIT WHEN C4%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('COUNT OF EMPLOYEES: '||COUNT);
END LOOP;
CLOSE C4;
END;
/