-- 20TH OCTOBER 2023

-- TABLES REQUIRED

CREATE TABLE STUD1(SID NUMBER(10) PRIMARY KEY, SNAME VARCHAR2(30), SADDRESS VARCHAR2(50), PHONE NUMBER(10),EMAIL VARCHAR2(50) CHECK (EMAIL LIKE '%__@%_.%'));

CREATE TABLE CLG (COLLEGEID NUMBER(10) PRIMARY KEY, COLLEGE_NAME VARCHAR2(50), COURSE VARCHAR2(50), FEES NUMBER(10));

CREATE TABLE STUDENT_COLLEGE (SID NUMBER(10) REFERENCES STUD1(SID), COLLEGEID NUMBER(10) REFERENCES CLG(COLLEGEID),ADMISSION_DATE DATE,SCHOLARSHIP VARCHAR2(6) CHECK(SCHOLARSHIP IN('YES','NO')));

-- INSERTING VALUES

-- STUD1 TABLE
INSERT INTO STUD1 VALUES(101,'HARSH','SANAND',9090808070,'HARSH@GMAIL.COM');
INSERT INTO STUD1 VALUES(102,'ALMAS','JUHAPURA',9988776655,'ALMAS@GMAIL.COM');
INSERT INTO STUD1 VALUES(103,'NIHAR','PG',1122334455,'NIHAR@GMAIL.COM');
INSERT INTO STUD1 VALUES(104,'KRISH','PRAHLADNAGAR',5566774433,'KRISHBHAIII@GMAIL.COM');
INSERT INTO STUD1 VALUES(105,'BURHAN','JUHAPURA',4567892345,'BURHAN@GMAIL.COM');

-- CLG TABLE
INSERT INTO CLG VALUES(1001,'LOK JAGRUTI','IMCA',23500);
INSERT INTO CLG VALUES(1002,'SILVER OAK','MBA',45500);
INSERT INTO CLG VALUES(1003,'GANPAT UNI','IMCA',28500);
INSERT INTO CLG VALUES(1004,'GUJARAT UNI','BSc',23500);
INSERT INTO CLG VALUES(1005,'LOK MANYA','IMCA',18500);

-- STUDENT_COLLEGE TABLE
INSERT INTO STUDENT_COLLEGE VALUES(101,1001,'5-JUL-2021','YES');
INSERT INTO STUDENT_COLLEGE VALUES(101,1001,'5-JUN-2021','YES');
INSERT INTO STUDENT_COLLEGE VALUES(103,1002,'5-OCT-2021','NO');
INSERT INTO STUDENT_COLLEGE VALUES(104,1003,'5-NOV-2021','NO');
INSERT INTO STUDENT_COLLEGE VALUES(105,1004,'5-JUN-2022','YES');

-- EXCERCISE

-- Q. 1 Write a pl/sql block to call a procedure that counts total students in 
-- each college and display them.

-- CREATING PROCEDURE FOR Q1

CREATE PROCEDURE CNTSTD(CIDD IN NUMBER,CID OUT NUMBER,CNT OUT NUMBER)
IS
BEGIN
SELECT COLLEGEID,COUNT(SID) INTO CID,CNT FROM STUDENT_COLLEGE HAVING COLLEGEID=CIDD;
END;
/


DECLARE
CIDD NUMBER;
CID NUMBER;
CNT NUMBER;
BEGIN
CNTSTD(&CIDD,CID,CNT);
DBMS_OUTPUT.PUT_LINE('COLLEGE ID: '||CID||CHR(10)||'NO OF STUDENTS: '||CNT);
END;
/

-- DECLARE
-- CID NUMBER;
-- CNT NUMBER;
-- CURSOR C1 IS SELECT COLLEGEID,COUNT(SID) FROM STUDENT_COLLEGE GROUP BY COLLEGEID;
-- BEGIN
-- OPEN C1;
-- LOOP
-- FETCH C1 INTO CID,CNT;
-- DBMS_OUTPUT.PUT_LINE('COLLEGE ID: '||CID||CHR(10)||'NO OF STUDENTS: '||CNT);
-- EXIT WHEN C1%NOTFOUND;
-- END LOOP;
-- CLOSE C1;
-- END;
-- /

-- Q.2  Write a pl/sql function that asks for admission date and displays count no of students college wise.

CREATE OR REPLACE FUNCTION CNT(DT DATE)
RETURN NUMBER
IS
CNTSTD NUMBER;
BEGIN
SELECT COUNT(SID) INTO CNTSTD FROM STUDENT_COLLEGE WHERE ADMISSION_DATE=DT;
RETURN CNTSTD;
END;
/

DECLARE
DT DATE;
COUNTT NUMBER;
BEGIN
COUNTT:=CNT('&DT');
DBMS_OUTPUT.PUT_LINE('COUNT: '||COUNTT);
END;
/

-- Q. 3 Write and call a parameterised cursor that takes college name as an argument and return its all details. Throw an exception when no college found.
--EXCEPTION NOT WORKING
DECLARE
CNAME VARCHAR2(30);
COL CLG%ROWTYPE;
CURSOR C2(CNAME VARCHAR2) IS SELECT * FROM CLG WHERE COLLEGE_NAME=CNAME;
BEGIN
OPEN C2('&CNAME');
FETCH C2 INTO COL;
IF C2%NOTFOUND THEN
CLOSE C2;
RAISE_APPLICATION_ERROR(-20001,'THE COLLEGE IS NOT FOUND');
ELSE 
DBMS_OUTPUT.PUT_LINE('COLLEGE ID: '||COL.COLLEGEID||CHR(9)||'COLLEGE NAME: '||COL.COLLEGE_NAME||CHR(9)||'COURSE: '||COL.COURSE||CHR(9)||'FEES: '||COL.FEES);
END IF;
CLOSE C2;
END;
/
