 -- DAY-21 PL/SQL
-- FOR LOOP CURSOR DEMO


DECLARE
CURSOR C1 IS SELECT * FROM DEMO;
BEGIN
FOR I IN C1 
LOOP
DBMS_OUTPUT.PUT_LINE('ID: '||I.ID||CHR(10)||'NAME: '||I.NAME);
END LOOP;
END;
/ 

-- INCOMPLETE WITN TWO PARAMETES WORKING WITH ONE
DECLARE
N1 VARCHAR2(50);
DID NUMBER;
CURSOR C1(DID IN NUMBER) IS SELECT NAME FROM DEMO WHERE ID=DID;
BEGIN
DID:=&DID;
FOR I IN C1(DID) 
LOOP
DBMS_OUTPUT.PUT_LINE('NAME: '||I.NAME);
END LOOP;
END;
/ 

-- WORKING ON EMP5 TABLE;

DECLARE
CURSOR C2(EID IN NUMBER,SAL IN NUMBER) IS SELECT * FROM EMP5 WHERE EMP_ID=EID AND EMP_SALARY>SAL;
BEGIN
FOR I IN C2(122,5000)
LOOP
DBMS_OUTPUT.PUT_LINE('EMP_NAME: '||I.EMP_NAME||CHR(10)||'SALARY: '||I.EMP_SALARY||CHR(10)||'EMP_ID: '||I.EMP_ID);
END LOOP;
END;
/

-- FOR LOOP CURSOR WITH PROCEDURE
-- NOT WORKING

CREATE OR REPLACE PROCEDURE ALX
IS 
CURSOR E1 IS SELECT * FROM EMPLOYEE;
BEGIN
FOR I IN E1
LOOP
DBMS_OUTPUT.PUT_LINE('EMP_ID: '||I.EMP_ID||CHR(10)||'EMP_NAME: '||I.EMP_NAME||CHR(10)||'EXPERIENCE: '||I.EXPERIENCE||CHR(10)||'CITY: '||I.CITY||CHR(10)||'SALARY: '||I.SALARY||CHR(10)||'MANAGER_ID: '||I.MANAGER_ID);
END LOOP;
END;
/