-- DEMO TABLES EMPP & DEPT FOR TODAY'S EXCERCISE

CREATE TABLE DEPT(DEPT_ID NUMBER(10) PRIMARY KEY,DNAME VARCHAR2(50),DLOC VARCHAR2(50));

CREATE TABLE EMPP(EID NUMBER(10),ENAME VARCHAR2(50),DEPT_ID NUMBER(10) REFERENCES DEPT(DEPT_ID),JOB VARCHAR2(50),SALARY NUMBER(10));

-- INSERTING VALUES
INSERT INTO EMPP VALUES(101,'HARSH',10,'MANAGER',50000);
INSERT INTO EMPP VALUES(102,'NIHAR',40,'ASSISTANT-MANAGER',40000);
INSERT INTO EMPP VALUES(103,'BURHAN',30,'TECH SUPPORT',40000);
INSERT INTO EMPP VALUES(104,'DHRUV',20,'HOD',80000);
INSERT INTO EMPP VALUES(105,'KRISH',20,'MARKETING MANAGER',30000);
INSERT INTO EMPP VALUES(106,'VIKAS',10,'CLERK',20000);
INSERT INTO EMPP VALUES(149,'ELVISH',10,'CLERK',10000);
INSERT INTO EMPP VALUES(150,'MAHESH',50,'CLERK',10000);
INSERT INTO EMPP VALUES(151,'RAMESH',50,'CLERK',16000);

-- DEPT TABLE

INSERT INTO DEPT VALUES(10,'SALES','AHMEDABAD');
INSERT INTO DEPT VALUES(20,'MARKETING','AHMEDABAD');
INSERT INTO DEPT VALUES(30,'HR','AHMEDABAD');
INSERT INTO DEPT VALUES(40,'PRODUCTION','AHMEDABAD');
INSERT INTO DEPT VALUES(50,'MCA','AHMEDABAD');

-- 1.	Write a program in PL/SQL to create a table-based record using the %ROWTYPE attribute where emp_id pass as an argument by user.

DECLARE
E1 EMPP%ROWTYPE;
CURSOR C1 IS SELECT * FROM EMPP WHERE EID=&EID;
BEGIN
OPEN C1;
LOOP
FETCH C1 INTO E1;
EXIT WHEN C1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('ID: '||E1.EID||CHR(10)||'NAME: '||E1.ENAME||CHR(10)||'DEPT ID: '||E1.DEPT_ID||CHR(10)||'JOB: '||E1.JOB||CHR(10)||'SALARY: '||E1.SALARY);
END LOOP;
CLOSE C1;
END;
/

-- 2.	Write a program in PL/SQL procedure to display a table based detail information for the employee of ID 149 from the employees table.

CREATE PROCEDURE DISPLAY(IDD IN NUMBER,ID OUT NUMBER,NAME OUT VARCHAR2,JOB OUT VARCHAR2,SAL OUT NUMBER)
IS
BEGIN
SELECT EID,ENAME,JOB,SALARY INTO ID,NAME,JOB,SAL FROM EMPP WHERE EID=IDD;
END;
/

-- EXECUTING
DECLARE
ID NUMBER;
NAME VARCHAR2(50);
JOB VARCHAR2(50);
SAL NUMBER;
BEGIN
DISPLAY(149,ID,NAME,JOB,SAL);
DBMS_OUTPUT.PUT_LINE('ID: '||ID||CHR(10)||'NAME: '||NAME||CHR(10)||'JOB: '||JOB||CHR(10)||'SAL: '||SAL);
END;
/

-- 3.	Write a program in PL/SQL to display a cursor based detail information of employees from employees table.[pass emp_id as parameter]

DECLARE
E2 EMPP%ROWTYPE;
ID NUMBER;
CURSOR P1(ID IN NUMBER)IS SELECT * FROM EMPP WHERE EID=ID;
BEGIN
OPEN P1(&ID);
LOOP
FETCH P1 INTO E2;
EXIT WHEN P1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('ID: '||E2.EID||CHR(10)||'NAME: '||E2.ENAME||CHR(10)||'DEPT ID: '||E2.DEPT_ID||CHR(10)||'JOB: '||E2.JOB||CHR(10)||'SALARY: '||E2.SALARY);
END LOOP;
CLOSE P1;
END;
/

-- 4.	Display dept and emp table data where job_id =’clerk’ and salary>3200 using explicit cursor with for loop.

DECLARE
CURSOR C4 IS SELECT DEPT.DEPT_ID,DEPT.DNAME,EMPP.EID,EMPP.ENAME,EMPP.JOB,EMPP.SALARY FROM DEPT,EMPP WHERE DEPT.DEPT_ID = EMPP.DEPT_ID AND EMPP.JOB='CLERK' AND EMPP.SALARY>3200;
BEGIN
FOR I IN C4
LOOP
DBMS_OUTPUT.PUT_LINE('DEPT ID: '||I.DEPT_ID||CHR(10)||'DEPT NAME: '||I.DNAME||CHR(10)||'EMP ID: '||I.EID||CHR(10)||'EMP NAME: '||I.ENAME||CHR(10)||'JOB: '||I.JOB||CHR(10)||'SALARY: '||I.SALARY);
END LOOP;
END;
/

-- 5.	Create a PL/SQL block to increase salary of employees in the department 50 using .if salary <15000 raise 0.15 else raise 0.10 using current of clause.

DECLARE
SAL NUMBER;
ID NUMBER;
CURSOR CC IS SELECT SALARY,EID FROM EMPP WHERE DEPT_ID=50;
BEGIN
OPEN CC;
LOOP
FETCH CC INTO SAL,ID;
EXIT WHEN CC%NOTFOUND;
IF SAL<15000 THEN
UPDATE EMPP SET SALARY=SALARY+(SALARY*0.15) WHERE EID=ID;
ELSE
UPDATE EMPP SET SALARY=SALARY+(SALARY*0.10) WHERE EID=ID;
END IF;
DBMS_OUTPUT.PUT_LINE('ROW UPDATED');
END LOOP;
CLOSE CC;
END;
/