-- DAY 15 PL/SQL PARAMETERISED CURSOR

-- CREATING TABLES
-- WORKER TABLE

CREATE TABLE WORKER(WORKER_ID NUMBER(10) PRIMARY KEY,NAME VARCHAR2(30),WAGE_PER_HOUR NUMBER(5),SPECIALISED_IN VARCHAR2(50));

-- COMPANY TABLE

CREATE TABLE COMPANY(COMPANY_ID NUMBER(10),COMPANY_NAME VARCHAR2(30),WORKER_ID NUMBER(10) REFERENCES WORKER(WORKER_ID));

-- INSERTING 5 RECORDS IN WORKER TABLE

INSERT INTO WORKER VALUES(101,'TOMMY',150,'WELDING');
INSERT INTO WORKER VALUES(102,'STEVE',120,'BRICKLAYING');
INSERT INTO WORKER VALUES(103,'BOB',100,'POLISHING');
INSERT INTO WORKER VALUES(104,'JACK',120,'BRICKLAYING');
INSERT INTO WORKER VALUES(105,'MAHESH',100,'MASONRY');
INSERT INTO WORKER VALUES(106,'MANISH',100,'POLISHING');
INSERT INTO WORKER VALUES(107,'RAMESH',120,'POLISHING');
INSERT INTO WORKER VALUES(108,'MUKESH',170,'POLISHING');
INSERT INTO WORKER VALUES(109,'GANESH',180,'POLISHING');

-- INSERTING 5 RECORDS IN COMPANY TABLE

INSERT INTO COMPANY VALUES(201,'WOODPECKER',101);
INSERT INTO COMPANY VALUES(201,'WOODPECKER',102);
INSERT INTO COMPANY VALUES(201,'WOODPECKER',103);
INSERT INTO COMPANY VALUES(202,'ABC COMPANY',102);
INSERT INTO COMPANY VALUES(202,'ABC COMPANY',101);
INSERT INTO COMPANY VALUES(202,'ABC COMPANY',103);
INSERT INTO COMPANY VALUES(203,'KKK COMPANY',103);
INSERT INTO COMPANY VALUES(203,'KKK COMPANY',105);
INSERT INTO COMPANY VALUES(204,'XYZ COMPANY',104);
INSERT INTO COMPANY VALUES(204,'XYZ COMPANY',106);
INSERT INTO COMPANY VALUES(205,'SSS COMPANY',105);

-- 1.	Using Parameterized Cursor to display the top five highest paid workers who are specialized in ‘POLISHING’.

DECLARE
WNAME WORKER.NAME%TYPE;
WPH WORKER.WAGE_PER_HOUR%TYPE;
CURSOR W1(SPEC VARCHAR2) IS SELECT NAME,WAGE_PER_HOUR FROM WORKER WHERE ROWNUM<=5 AND SPECIALISED_IN=SPEC ORDER BY WAGE_PER_HOUR DESC;
BEGIN
OPEN W1('POLISHING');
DBMS_OUTPUT.PUT_LINE('WORKERS SPECIALISED IN POLISHING AND EARNING HIGHEST'||CHR(10));
LOOP
FETCH W1 INTO WNAME,WPH;
EXIT WHEN W1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('NAME: '||WNAME||CHR(10)||'WAGE PER HOUR:'||WPH);
END LOOP;
CLOSE W1;
END;
/

-- 2.	Using Parameterized Cursor to display worker name who got highest wages than ‘Manish’.

DECLARE
WNAME WORKER.NAME%TYPE;
CURSOR W2(NAM VARCHAR) IS SELECT NAME FROM WORKER WHERE WAGE_PER_HOUR > (SELECT WAGE_PER_HOUR FROM WORKER WHERE NAME='MANISH') AND SPECIALISED_IN='POLISHING' ORDER BY WAGE_PER_HOUR DESC;
BEGIN
OPEN W2('MANISH');
DBMS_OUTPUT.PUT_LINE('WORKERS EARNING MORE THAN MANISH:'||CHR(10));
LOOP
FETCH W2 INTO WNAME;
EXIT WHEN W2%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('WORKER NAME: '||WNAME);
END LOOP;
CLOSE W2;
END;
/

-- 3.	Write a PL/SQL cursor asks for company name and display its ‘Ahmedabad’ Worker.
-- INCOMPLETE

DECLARE
-- CNAME COMPANY.COMPANY_NAME%TYPE;
WNAME WORKER.NAME%TYPE;
CURSOR W3(CNAME VARCHAR) 
BEGIN
END;
/

-- 4.	Create a parameterized cursor that updates the wages of employees based on their specialization.
-- NOT WORKING
DECLARE
CURSOR W4(SPEC VARCHAR2) IS UPDATE WORKER SET WAGE_PER_HOUR=WAGE_PER_HOUR + WAGE_PER_HOUR * 0.1 WHERE SPECIALISED_IN=SPEC;
SPEC VARCHAR2(10) :='POLISHING';
BEGIN
OPEN W4(SPEC);
CLOSE W4;
DBMS_OUTPUT.PUT_LINE('WAGES UPDATED');
END;
/

