-- 20TH OCTOBER 2023
-- DAY 21

-- TABLES REQUIRED
-- STUDENT2 TABLE WITH 5 RECORDS
CREATE TABLE STUDENT2(STU_ID NUMBER(10) PRIMARY KEY, STU_NAME VARCHAR2(50), DATE_OF_BIRTH DATE,ADDRESS VARCHAR(100));

INSERT INTO STUDENT2 VALUES(101,'HARSH','13-OCT-2004','SANAND');
INSERT INTO STUDENT2 VALUES(102,'NIHAR','13-MAY-2004','PG');
INSERT INTO STUDENT2 VALUES(103,'KRISH','13-APR-2005','PRAHLADNAGAR');
INSERT INTO STUDENT2 VALUES(104,'ADITYA','13-JUL-2003','AHMEDABAD');
INSERT INTO STUDENT2 VALUES(105,'VIKAS','13-FEB-2014','BARODA');

-- SHOW TABLE WITH 5 RECORDS
CREATE TABLE SHOW(SHOW_ID NUMBER(10), SHOW_NAME VARCHAR2(50),LOCATION VARCHAR2(30), MAX_CAPACITY NUMBER CHECK(MAX_CAPACITY > 0),STU_ID NUMBER(10) REFERENCES STUDENT2(STU_ID),RATE NUMBER(10));

INSERT INTO SHOW VALUES(111,'KALANJALI','LJMCA',100,101,100);
INSERT INTO SHOW VALUES(111,'KALANJALI','LJMCA',100,102,100);
INSERT INTO SHOW VALUES(111,'KALANJALI','LJMCA',100,103,100);
INSERT INTO SHOW VALUES(111,'KALANJALI','LJMCA',100,104,100);
INSERT INTO SHOW VALUES(111,'MAGIC SHOW','SANAND',100,101,250);
INSERT INTO SHOW VALUES(111,'MAGIC SHOW','SANAND',100,103,250);
INSERT INTO SHOW VALUES(111,'MAGIC SHOW','SANAND',100,105,250);
INSERT INTO SHOW VALUES(111,'CRL - ESPORTS','AHMEDABAD',100,103,500);
INSERT INTO SHOW VALUES(111,'CRL - ESPORTS','AHMEDABAD',100,104,500);
INSERT INTO SHOW VALUES(111,'CRL - ESPORTS','AHMEDABAD',100,105,500);
INSERT INTO SHOW VALUES(111,'CRL - ESPORTS','AHMEDABAD',100,102,500);
INSERT INTO SHOW VALUES(111,'COMEDY','AHMEDABAD',500,102,150);
INSERT INTO SHOW VALUES(111,'COMEDY','AHMEDABAD',500,105,150);

-- QUESTIONS AND SOLUTIONS
-- 1.	Write a pl/sql block to call a procedure that counts total students in each show.

-- PROCEDURE FOR ABOVE
CREATE PROCEDURE COUNT_STU1
IS
CURSOR P1 IS SELECT SHOW_NAME,COUNT(STU_ID) FROM SHOW GROUP BY SHOW_NAME;
BEGIN
FOR I IN P1
LOOP
DBMS_OUTPUT.PUT_LINE('SHOW NAME: '||I.SHOW_NAME); -- DOESNT SUPPORT AGGREGATE FUNCTIONS
END LOOP;
END;
/

-- BLOCK TO CALL THE ABOVE PROCEDURE
BEGIN
COUNT_STU1();
END;
/

-- ALTERNATE WAY TO CALL PROCEDURE
EXECUTE COUNT_STU1();

-- 2.	Write and call a parameterized cursor that takes show name as an argument using procedure and return its maximum capacity.

CREATE PROCEDURE RETURNCAP(SNAME IN VARCHAR2,MAXCAP OUT NUMBER)
IS
BEGIN
SELECT MAX_CAPACITY INTO MAXCAP FROM SHOW WHERE SHOW_NAME=SNAME AND ROWNUM=1;
END;
/

-- EXECUTING ABOVE
DECLARE
MAXCAP NUMBER;
BEGIN
EXECUTE RETURNCAP('CRL - ESPORTS',MAXCAP);
DBMS_OUTPUT.PUT_LINE('MAXCAP: '||MAXCAP);
END;
/

-- USING BLOCK
DECLARE
MAXCAP NUMBER;
BEGIN
RETURNCAP('CRL - ESPORTS',MAXCAP);
DBMS_OUTPUT.PUT_LINE('MAXCAP: '||MAXCAP);
END;
/

-- 3.	Display all the details of show using a cursor-FOR loop.

DECLARE
CURSOR P4 IS SELECT * FROM SHOW;
BEGIN
FOR I IN P4
LOOP
DBMS_OUTPUT.PUT_LINE('SHOW NAME: '||I.SHOW_NAME||CHR(10)||'RATE: '||I.RATE||CHR(10)||'LOCATION: '||I.LOCATION||CHR(10)||'MAX CAP: '||I.MAX_CAPACITY);
END LOOP;
END;
/

-- 4.	Create a procedure that will give a 10% raise to all students whose live in Ahmedabad.

CREATE PROCEDURE UPD
IS BEGIN
UPDATE SHOW SET MAX_CAPACITY=MAX_CAPACITY+MAX_CAPACITY*0.1 WHERE LOCATION = 'AHMEDABAD';
END;
/

DECLARE
CURSOR P5 IS SELECT SHOW_NAME,LOCATION,MAX_CAPACITY FROM SHOW WHERE LOCATION = 'AHMEDABAD';
BEGIN
FOR I IN P5
LOOP
DBMS_OUTPUT.PUT_LINE('SHOW NAME: '||I.SHOW_NAME||CHR(10)||'LOCATION: '||I.LOCATION||CHR(10)||'CAPACITY: '||I.MAX_CAPACITY);
END LOOP;
END;
/