-- DAY 24 --
-- FUNCTION IN CURSOR --
-- TABLES USED ARE 'EMPLOYEE'

-- FUNCTION THAT RETURNS SALARY WITH 1000 INCREMENT --
CREATE OR REPLACE FUNCTION CALSAL(EID IN NUMBER)
RETURN NUMBER
IS
CSAL NUMBER;
BEGIN
SELECT SALARY+1000 INTO CSAL FROM EMPLOYEE WHERE EMP_ID=EID;
RETURN CSAL;
END;
/

-- CALLING ABOVE FUNCTION IN CURSOR --
DECLARE
CURSOR C1 IS SELECT EMP_ID,EMP_NAME,CALSAL(108) AS INCREMENTED_SALARY FROM EMPLOYEE WHERE EMP_ID=108;
ENO EMPLOYEE.EMP_ID%TYPE;
ENAME EMPLOYEE.EMP_NAME%TYPE;
ESAL EMPLOYEE.SALARY%TYPE;
BEGIN
OPEN C1;
LOOP
FETCH C1 INTO ENO,ENAME,ESAL;
EXIT WHEN C1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('EMP ID: '||ENO||CHR(10)||'EMPLOYEE NAME: '||ENAME||CHR(10)||'INCREASED SALARY: '||ESAL);
END LOOP;
CLOSE C1;
END;
/