-- DAY 11
-- IMPLICIT CURSOR IN SQL
DECLARE
RCOUNT NUMBER;
BEGIN
UPDATE STUDENT SET LNAME='MINDI' WHERE ROLLNO=7;
IF SQL%NOTFOUND THEN
DBMS_OUTPUT.PUT_LINE('DATA NOT FOUND!!');
ELSIF SQL%FOUND THEN
RCOUNT:=SQL%ROWCOUNT;
DBMS_OUTPUT.PUT_LINE('NO OF ROWS AFFECTED: '||RCOUNT);
END IF;
END;
/

-- DAY 11 ESSENTIAL Q1
DECLARE
RCOUNT NUMBER;
BEGIN
UPDATE EMPLOYEE SET SALARY=SALARY+SALARY*0.15 WHERE EID IN(SELECT EID FROM EMPLOYEE);
IF SQL%NOTFOUND THEN
DBMS_OUTPUT.PUT_LINE('DATA NOT FOUND!!');
ELSIF SQL%FOUND THEN
RCOUNT:=SQL%ROWCOUNT;
DBMS_OUTPUT.PUT_LINE('NO OF ROWS AFFECTED: '||RCOUNT);
END IF;
END;
/

-- DAY 11 ESSENTIAL Q2

-- INSERTING DEMO VALUES FOR THIS QUESTION
INSERT INTO EMPLOYEE VALUES(107,'NIHAR',15,'ACCOUNTING',25000);
INSERT INTO EMPLOYEE VALUES(108,'HARSH',16,'ACCOUNTING',30000);
INSERT INTO EMPLOYEE VALUES(109,'DHRUV',17,'ACCOUNTING',27500);

-- SQL BLOCK FOR Q2
DECLARE
RCOUNT NUMBER;
COUNTT NUMBER;
BEGIN
SELECT COUNT(JOB) INTO COUNTT FROM EMPLOYEE WHERE JOB='ACCOUNTING';
UPDATE EMPLOYEE SET SALARY=SALARY+SALARY*0.10 WHERE JOB='ACCOUNTING';
IF SQL%NOTFOUND THEN
DBMS_OUTPUT.PUT_LINE('DATA NOT FOUND!!');
ELSIF SQL%FOUND THEN
RCOUNT:=SQL%ROWCOUNT;
DBMS_OUTPUT.PUT_LINE('NO OF ROWS AFFECTED: '||RCOUNT);
DBMS_OUTPUT.PUT_LINE('NO OF ACCOUNTANT: '||COUNTT);
END IF;
END;
/

-- DAY 11 Q3 ESSENTIAL INCOMPLETE!!
DECLARE
BEGIN

END;
/

-- EXPLICIT CURSOR
DECLARE
ROLLNO STUDENT.ROLLNO%TYPE;
FNAME STUDENT.FNAME%TYPE;
CURSOR C1 IS SELECT ROLLNO,FNAME INTO ROLLNO,FNAME FROM STUDENT WHERE FNAME LIKE '%H';
BEGIN
OPEN C1;
LOOP
FETCH C1 INTO ROLLNO,FNAME;
EXIT WHEN C1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE(ROLLNO||' : '||FNAME);
END LOOP;
CLOSE C1;
END;
/

-- DAY 11 EXCERCISES

-- 1.	Write a PL/SQL block that declares a cursor named emp_cursor to retrieve the names of employees from an employees table. Open the cursor and fetch the names into a variable named emp_name.

-- 2.	Extend the PL/SQL block from question 1 to handle the case when no records are found in the cursor. If no records are found, print a message indicating so.

DECLARE
EMP_NAME EMPLOYEE.ENAME%TYPE;
CURSOR EMP_CURSOR IS SELECT ENAME FROM EMPLOYEE WHERE ENAME LIKE 'X%'; 
BEGIN
OPEN EMP_CURSOR;
LOOP
FETCH EMP_CURSOR INTO EMP_NAME;
EXIT WHEN EMP_CURSOR%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('NAMES OF EMPLOYEES: '||EMP_NAME);
END LOOP;
IF EMP_CURSOR%NOTFOUND THEN
DBMS_OUTPUT.PUT_LINE('NO DATA FOUND!!');
END IF;
CLOSE EMP_CURSOR;
END;
/

-- 3.	Write a PL/SQL block that uses a cursor to update the salary of employees with a specific job title in an employees table.
-- INCOMPLETE
DECLARE
NAME EMPLOYEE.ENAME%TYPE;
SAL EMPLOYEE.SALARY%TYPE;
TITLE EMPLOYEE.JOB%TYPE;
CURSOR E1 IS SELECT ENAME,SALARY INTO NAME,SAL FROM EMPLOYEE WHERE JOB='&TITLE';
BEGIN
OPEN E1;
LOOP
FETCH E1 INTO NAME,TITLE;
EXIT WHEN E1%NOTFOUND;
UPDATE EMPLOYEE SET SALARY=SALARY+SALARY*0.1 WHERE JOB='CLERK';
END LOOP;
CLOSE E1;
END;
/

-- 4.	Write a PL/SQL block that uses a cursor to find the details of the employee whose name start with k and end with a.
DECLARE
NAME EMPLOYEE.ENAME%TYPE;
CURSOR E2 IS SELECT ENAME  FROM EMPLOYEE WHERE ENAME LIKE 'K%A';
BEGIN
OPEN E2;
LOOP
FETCH E2 INTO NAME;
EXIT WHEN E2%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('NAME: '||NAME);
END LOOP;
CLOSE E2;
END;
/

-- 5.	Write a PL/SQL block that uses a cursor to find the details of the employee whose salary is not more than 15000.
DECLARE
ID EMPLOYEE.EID%TYPE;
NAME EMPLOYEE.ENAME%TYPE;
TITLE EMPLOYEE.JOB%TYPE;
CURSOR E3 IS SELECT EID,ENAME,JOB FROM EMPLOYEE WHERE NOT(SALARY>15000);
BEGIN
OPEN E3;
LOOP
FETCH E3 INTO ID,NAME,TITLE;
EXIT WHEN E3%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('ID: '||ID);
DBMS_OUTPUT.PUT_LINE('NAME: '||NAME);
DBMS_OUTPUT.PUT_LINE('JOB: '||TITLE);
END LOOP;
CLOSE E3;
END;
/

-- 6.	Write a PL/SQL block that uses a cursor to find the details of the employee who work in IT department and joining data is 2010.

DECLARE
ID EMPLOYEE.EID%TYPE;
NAME EMPLOYEE.ENAME%TYPE;
PAISA EMPLOYEE.SALARY%TYPE;
CURSOR EMP1 IS SELECT EID,ENAME,SALARY FROM EMP3 WHERE JOIN_DATE BETWEEN '1-JAN-2010' AND '31-DEC-2010';
BEGIN
DBMS_OUTPUT.PUT_LINE('DETAILS OF EMPLOYEES WHO ARE SINCE 2010!!: ');
OPEN EMP1;
LOOP
FETCH EMP1 INTO ID,NAME,PAISA;
EXIT WHEN EMP1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('ID: '||ID);
DBMS_OUTPUT.PUT_LINE('NAME: '||NAME);
DBMS_OUTPUT.PUT_LINE('SALARY: '||PAISA);
END LOOP;
CLOSE EMP1;
END;
/

-- ROUGH QUERIES
UPDATE EMPLOYEE SET SALARY=10000;
ALTER TABLE EMP3 ADD(JOIN_DATE DATE);

INSERT INTO EMP3 VALUES(101,'MAHESH',15000,'10-JAN-2010');
INSERT INTO EMP3 VALUES(102,'RAMESH',20000,'10-FEB-2010');
INSERT INTO EMP3 VALUES(103,'SURESH',12500,'10-MAR-2009');
INSERT INTO EMP3 VALUES(104,'NARESH',10000,'10-JUN-2011');
INSERT INTO EMP3 VALUES(105,'DIKESH',17500,'10-JUL-2013');
INSERT INTO EMP3 VALUES(106,'DHRUV',15000,'10-OCT-2004');
INSERT INTO EMP3 VALUES(107,'BURHAN',22500,'10-DEC-2009');
INSERT INTO EMP3 VALUES(108,'KAMIYA',25000,'17-DEC-2007');
INSERT INTO EMP3 VALUES(109,'KRISHA',17500,'17-FEB-2007');

-- MORE ROUGH QUERIES!!!!
INSERT INTO EMPLOYEE VALUES(110,'KAMIYA','IT','SYS ADMIN',50000);
INSERT INTO EMPLOYEE VALUES(111,'KRISHA','MEDICAL','NURSE',30000);