-- DAY 12 EXCERCISE!!
-- 5.	Write a PL/SQL block that uses a cursor to find the details of the employee who does not belongs to ‘sales’ department.

DECLARE
ID EMPLOYEE.EID%TYPE;
NAME EMPLOYEE.ENAME%TYPE;
TITLE EMPLOYEE.JOB%TYPE;
CURSOR E1 IS SELECT EID,ENAME,JOB FROM EMPLOYEE WHERE  DEPT NOT IN('SALES');
BEGIN
OPEN E1;
LOOP
FETCH E1 INTO ID,NAME,TITLE;
EXIT WHEN E1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('ID: '||ID);
DBMS_OUTPUT.PUT_LINE('NAME: '||NAME);
DBMS_OUTPUT.PUT_LINE('JOB: '||TITLE);
END LOOP;
CLOSE E1;
END;
/

-- 6.	Write a PL/SQL block, which takes as input the employee name and displays all the details of the employee.

DECLARE
NAME EMPLOYEE.ENAME%TYPE;
ID EMPLOYEE.EID%TYPE;
TITLE EMPLOYEE.JOB%TYPE;
CURSOR E2 IS SELECT EID,ENAME,JOB FROM EMPLOYEE WHERE ENAME='&NAME';
BEGIN
OPEN E2;
LOOP
FETCH E2 INTO ID,NAME,TITLE;
EXIT WHEN E2%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('ID: '||ID);
DBMS_OUTPUT.PUT_LINE('NAME: '||NAME);
DBMS_OUTPUT.PUT_LINE('TITLE: '||TITLE);
END LOOP;
CLOSE E2;
END;
/

-- 7.	Write a PL/SQL block,  that uses a cursor to find the maximum salary of an employee.

DECLARE
SAL EMPLOYEE.SALARY%TYPE;
CURSOR E3 IS SELECT MAX(SALARY) FROM EMPLOYEE;
BEGIN
OPEN E3;
LOOP
FETCH E3 INTO SAL;
EXIT WHEN E3%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('MAXIMUM SALARY: '||SAL);
END LOOP;
CLOSE E3;
END;
/

-- 8.	Write a PL/SQL block, that uses a cursor display the salary of the youngest employee in the IT department.

DECLARE
SAL EMPLOYEE.SALARY%TYPE;
CURSOR E4 IS SELECT SALARY FROM EMP3 WHERE JOIN_DATE = (SELECT MAX(JOIN_DATE) FROM EMP3);
BEGIN
OPEN E4;
LOOP
FETCH E4 INTO SAL;
EXIT WHEN E4%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('SALARY OF YOUNGEST EMPLOYEE: '||SAL);
END LOOP;
CLOSE E4;
END;
/