-- DAY - 20 
-- 14TH OCTOBER 2023
-- Question 1:Write a PL/SQL procedure named add_competion that inserts a new competition into the competition table. 
-- The procedure should take the following input parameters:
-- compe_id 
-- compe_name 

-- TABLES REQUIRED

CREATE TABLE STUD( STUD_ID NUMBER PRIMARY KEY, STU_NAME VARCHAR2(100), AGE NUMBER ); 

CREATE TABLE COMP ( COMP_ID NUMBER, COMP_NAME VARCHAR2(100), COMP_MARKS  NUMBER, STUD_ID NUMBER REFERENCES STUD(STUD_ID)); 

-- INSERTING SOME VALUES

-- STUDENT TABLE
INSERT INTO STUD VALUES(111,'KRISH BHAIII',18);
INSERT INTO STUD VALUES(112,'ELVISH BHAIII',21);
INSERT INTO STUD VALUES(113,'VIKAS BHAIII',5);
INSERT INTO STUD VALUES(114,'BURHAN',19);
INSERT INTO STUD VALUES(115,'ADITYA',19);

-- COMPETITION TABLE
INSERT INTO COMP VALUES(101,'DRAWING',80,111);
INSERT INTO COMP VALUES(101,'DRAWING',80,112);
INSERT INTO COMP VALUES(102,'HANDWRITING',60,113);
INSERT INTO COMP VALUES(102,'HANDWRITING',60,114);
INSERT INTO COMP VALUES(103,'SPORTS',75,113);
INSERT INTO COMP VALUES(103,'SPORTS',75,114);
INSERT INTO COMP VALUES(104,'DANCING',50,111);
INSERT INTO COMP VALUES(104,'DANCING',50,112);
INSERT INTO COMP VALUES(105,'SINGING',40,115);
INSERT INTO COMP VALUES(105,'SINGING',40,113);
INSERT INTO COMP VALUES(103,'SPORTS',40,111);
INSERT INTO COMP VALUES(103,'SPORTS',40,112);


-- PROCEDURE FOR QUESTION 1

CREATE PROCEDURE ADD_COMPETITION (C_ID IN NUMBER,C_NAME IN VARCHAR2,C_MARKS IN NUMBER,S_ID IN NUMBER)
IS BEGIN
INSERT INTO COMP VALUES(C_ID,C_NAME,C_MARKS,S_ID);
END;
/

-- EXECUTION OF ABOVE PROCEDURE

BEGIN
ADD_COMPETITION(106,'CODING',100,114);
DBMS_OUTPUT.PUT_LINE('ROW ADDED');
END;
/

-- QUESTION 2: Write a PL/SQL procedure named update_competition that updates the competition ‘Chess’. The procedure should take the following input parameters:
-- compe_id 
-- Competition_name (New)

-- PROCEDURE FOR QUESTION 2

CREATE PROCEDURE UPDATE_COMPETITION (C_ID IN NUMBER,C_NAME IN VARCHAR2)
IS BEGIN
UPDATE COMP SET COMP_NAME=C_NAME WHERE COMP_ID=C_ID;
END;
/

-- EXECUTION OF ABOVE PROCEDURE

BEGIN
UPDATE_COMPETITION(104,'CHESS');
DBMS_OUTPUT.PUT_LINE('ROW UPDATED!!');
END;
/

-- QUESTION 3 : Create a PL/SQL procedure named retrieves the stud_id and competition name of an student based on their ID. The procedure should take the following input parameter:
-- stud_id 
-- The procedure should output the following:
-- STUD_ID
-- COMP_NAME

-- PROCEDURE FOR QUESTION 3:

CREATE PROCEDURE RETRIEVE (S_ID IN NUMBER,ST_ID OUT NUMBER,C_NAME OUT VARCHAR2)
IS  BEGIN
SELECT STUD_ID,COMP_NAME INTO ST_ID,C_NAME FROM COMP WHERE STUD_ID=S_ID;
END;
/

-- EXECUTION OF ABOVE PROCEDURE
DECLARE
C1 COMP%ROWTYPE;
BEGIN
RETRIEVE(116,C1.STUD_ID,C1.COMP_NAME);
DBMS_OUTPUT.PUT_LINE('DATA RETRIEVED:'||CHR(10)||'STUDENT ID: '||C1.STUD_ID||CHR(10)||'COMPETITION NAME: '||C1.COMP_NAME);
END;
/

-- QUESTION 4: Write a PL/SQL procedure named delete_competition that deletes competition details based on stu_ ID. The procedure should take the following input parameter:
-- •	stuD_id 

-- PROCEDURE FOR QUESTION 4

CREATE PROCEDURE DEL_COMP(SID IN NUMBER)
IS  BEGIN
DELETE COMP WHERE STUD_ID=SID;
END;
/

-- EXECUTION OF ABOVE PROCEDURE

BEGIN
DEL_COMP(115);
DBMS_OUTPUT.PUT_LINE('ROW DELETED!!!');
END;
/

-- QUESTION 5: Write a PL/SQL procedure named count_student based on comp_ ID. The procedure should take the following input parameter:
-- •	comp_id 

CREATE PROCEDURE COUNT_STUDENT(CID IN NUMBER,CC OUT NUMBER)
IS  BEGIN
SELECT COUNT(STUD_ID) INTO CC FROM COMP WHERE COMP_ID=CID;
END;
/

-- EXECUTION OF ABOVE PROCEDURE
DECLARE
ID NUMBER;
CNT NUMBER;
BEGIN
ID:=&ID;
COUNT_STUDENT(ID,CNT);
DBMS_OUTPUT.PUT_LINE('COUNT: '||CNT||CHR(10)||'ID: '||ID);
END;
/