-- IF ELSE IN SQL
DECLARE
JAVA NUMBER(3);
PLSQL NUMBER(3);
DS NUMBER(3);
ADDITION NUMBER(3);
PERCENT FLOAT(3);
BEGIN
JAVA:=&JAVA;
PL/SQL:=&PLSQL;
DS:=&DS;
ADD=JAVA + PLSQL +DS;
PERCENT=(ADD*100)/300;
IF PERCENT>70 THEN
DBMS_OUTPUT.PUT_LINE('DISTINCTION!!!');
ELSIF PERCENT>60 THEN
DBMS_OUTPUT.PUT_LINE('FIRST CLASS!!');
ELSIF PERCENT>50 THEN
DBMS_OUTPUT.PUT_LINE('SECOND CLASS!');
ELSIF PERCENT>40 THEN
DBMS_OUTPUT.PUT_LINE('PASSED');
ELSE
DBMS_OUTPUT.PUT_LINE('FAILED!!!!!!!');
END;
/