-- Item Master (Item Code, Item Name, Price, Unit)
-- Stock (Item Code, Purchased Qty, Sold Qty)

-- 1. Write a trigger before update for each row not allowing to update if Sold Qty > Purchased Qty.
-- 2. Write a procedure to insert the new record in Item Master table. If Item is already exist than raise the exception.
-- 3.Write a function which accept the Item Name as an argument and return the price of that item.If itemname does not exists than raise the exception.
-- 4.Write a procedure to display stock detail of the given item name in proper format.

CREATE TABLE ITEM_MASTER(ITEM_CODE NUMBER(10) PRIMARY KEY,ITEM_NAME VARCHAR2(50),PRICE NUMBER(10),UNIT NUMBER(10));
--
INSERT INTO ITEM_MASTER VALUES(101,'GeFORCE GTX 1660',17500,1);
INSERT INTO ITEM_MASTER VALUES(102,'AMD RADON RX 6600',20500,1);
INSERT INTO ITEM_MASTER VALUES(103,'AMD RADON RX 6600XT',22500,1);
INSERT INTO ITEM_MASTER VALUES(104,'GeFORCE RTX 4090',112000,1);
--
CREATE TABLE STOCK(ITEM_CODE NUMBER(10) REFERENCES ITEM_MASTER(ITEM_CODE),P_QTY NUMBER(10),S_QTY NUMBER(10));
--
INSERT INTO STOCK VALUES(101,50,10);
INSERT INTO STOCK VALUES(102,50,20);
INSERT INTO STOCK VALUES(103,50,35);
INSERT INTO STOCK VALUES(104,50,0);

--ANSWER 1:

CREATE OR REPLACE TRIGGER TRR1
BEFORE UPDATE ON STOCK
FOR EACH ROW
BEGIN
IF :NEW.S_QTY > :OLD.P_QTY
THEN
RAISE_APPLICATION_ERROR(-20001,'SOLD QUANTITY CANNOT EXCEED PURCHASED QTY I.E ITEM OUT OF STOCKS');
ELSE
DBMS_OUTPUT.PUT_LINE('TABLE UPDATED SUCCESSFULLY!!');
END IF;
END;
/

--ANSWER 2:


CREATE OR REPLACE PROCEDURE "ADD_ITEM"(ICD IN ITEM_MASTER.ITEM_CODE%TYPE,INAME IN ITEM_MASTER.ITEM_NAME%TYPE,IPRICE IN ITEM_MASTER.PRICE%TYPE,IUNIT IN ITEM_MASTER.UNIT%TYPE)
IS
BEGIN
INSERT INTO ITEM_MASTER VALUES(ICD,INAME,PRICE,IUNIT);
DBMS_OUTPUT.PUT_LINE('INSERTED SUCCESSFULLY');
END;
/


/*
CREATE TABLE IMASTER(ICODE NUMBER(10),ITEM_NAME VARCHAR2(50),ITEM_PRICE NUMBER(10),ITEM_UNIT NUMBER(10));

`
SELECT ITEM_CODE INTO CD FROM ITEM_MASTER WHERE ITEM_CODE=ICD;
END IF;
IF CD IS NULL
THEN
ELSE
RAISE_APPLICATION_ERROR(-20002,'ITEM ALREADY EXIST IN TABLE!!');
*/

-- WORKING ON TABLE W/O PRIMARY KEYS --
CREATE PROCEDURE "INS_VAL4" (ICD IN NUMBER,INAME IN VARCHAR2,IPRICE IN NUMBER,IUNIT IN NUMBER)
IS
BEGIN
INSERT INTO IMASTER VALUES(ICD,INAME,IPRICE,IUNIT);
END;
/
-----------------------------------------
CREATE TABLE MASTER_ITEM(CODE NUMBER(10) PRIMARY KEY,I_NAME VARCHAR2(50),I_PRICE NUMBER(10),NO_UNIT NUMBER(10));

INSERT INTO MASTER_ITEM VALUES(101,'GeFORCE GTX 1660',17500,1);
INSERT INTO MASTER_ITEM VALUES(102,'AMD RADON RX 6600',20500,1);
INSERT INTO MASTER_ITEM VALUES(103,'AMD RADON RX 6600XT',22500,1);
INSERT INTO MASTER_ITEM VALUES(104,'GeFORCE RTX 4090',112000,1);

CREATE TABLE STOCK2(CODE NUMBER(10) REFERENCES MASTER_ITEM(CODE),P_QTY NUMBER(10),S_QTY NUMBER(10));

INSERT INTO STOCK2 VALUES(101,50,10);
INSERT INTO STOCK2 VALUES(102,50,20);
INSERT INTO STOCK2 VALUES(103,50,35);
INSERT INTO STOCK2 VALUES(104,50,0);


CREATE OR REPLACE PROCEDURE INS_ITEM(ICD IN MASTER_ITEM.CODE%TYPE,INAME IN MASTER_ITEM.I_NAME%TYPE,PRICE IN MASTER_ITEM.I_PRICE%TYPE,UNIT IN MASTER_ITEM.NO_UNIT%TYPE)
IS
BEGIN
INSERT INTO MASTER_ITEM VALUES(ICD,INAME,PRICE,UNIT);
END;
/

DECLARE
I NUMBER;
N VARCHAR2(50);
P NUMBER;
U NUMBER;
BEGIN
INS_ITEM(&I,'&N',&P,&U);
END;
/


-- ANSWER 3

CREATE OR REPLACE FUNCTION FIND_PRICE(INAME IN VARCHAR2)
RETURN NUMBER
IS
COST NUMBER;
BEGIN
SELECT PRICE INTO COST FROM ITEM_MASTER WHERE ITEM_NAME=INAME;
RETURN COST;
-- RAISE_APPLICATION_ERROR(-20069,'NO PRICE FOUND');
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('KRISH BHAI K AAGE KOI BOL SAKTA HAI KYAAA!!!');
END;
/

DECLARE
CST NUMBER;
-- INAME VARCHAR2(50);
BEGIN
CST := FIND_PRICE('&INAME');
DBMS_OUTPUT.PUT_LINE('PRICE: '||CST);
END;
/

-- ANSWER 4:

CREATE OR REPLACE PROCEDURE DISPLAY_ITEM(ICD IN NUMBER)
IS
IM ITEM_MASTER%ROWTYPE;
BEGIN
SELECT * INTO IM FROM ITEM_MASTER WHERE ITEM_CODE=ICD;
DBMS_OUTPUT.PUT_LINE('ITEM DETAILS:');
DBMS_OUTPUT.PUT_LINE('ITEM CODE: '||IM.ITEM_CODE||CHR(10)||'ITEM NAME: '||IM.ITEM_NAME||CHR(10)||'PRICE: '||IM.PRICE||CHR(10)||'UNITS :'||IM.UNIT);
END;
/

DECLARE
ICD NUMBER;
BEGIN
DISPLAY_ITEM(&ICD);
END;
/