-- DAY 19  13TH OCTOBER-2023
-- SQL PROCEDURE
-- DEMO TABLE
CREATE TABLE DEMO(ID NUMBER(10),NAME VARCHAR2(50));

-- INSERTING DEMO VALUES
INSERT INTO DEMO VALUES(101,'ALMAS');

-- PROCEDURE TO INSERT VALUES IN TABLE
CREATE PROCEDURE "INS_VAL" (ID IN NUMBER,NAME IN VARCHAR2)
IS
BEGIN
INSERT INTO DEMO VALUES(ID,NAME);
END;
/

-- IF SUCCESSFUL "PL/SQL PROCEDURE SUCESSFULLY COMPLETED" WILL SHOW
-- TO CALL PROCEDURE WRITE....


 -- SYNTAX: 
 -- BEGIN PROCEDURE_NAME(PARAMETER 1,PARAMETER 2....N);
 -- END;
 -- /
 
BEGIN INS_VAL(103,'HARSH');
DBMS_OUTPUT.PUT_LINE('VALUE INSERTED');
END;
/