DECLARE
S1 STUDENT%ROWTYPE;
BEGIN
SELECT * INTO S1 FROM STUDENT WHERE ROLLNO=1;
DBMS_OUTPUT.PUT_LINE('STUDENT ROLL NO: '||S1.ROLLNO||' STUDENT NAME: '||S1.FNAME||' STUDENT LNAME: '||S1.LNAME||' STUDENT DOB: '||S1.DOB);
END;
/
