-- IF ELSE IN SQL
DECLARE
JAVA NUMBER(3);
PLSQL NUMBER(3);
DS NUMBER(3);
ADDITION NUMBER(3);
PERCENT FLOAT(10);
BEGIN
JAVA:=&JAVA;
PLSQL:=&PLSQL;
DS:=&DS;
ADDITION:=JAVA + PLSQL +DS;
PERCENT:=(ADDITION*100)/300;
IF PERCENT>70 THEN
DBMS_OUTPUT.PUT_LINE('DISTINCTION!!! '||PERCENT);
ELSIF PERCENT>60 THEN
DBMS_OUTPUT.PUT_LINE('FIRST CLASS!! '||PERCENT);
ELSIF PERCENT>50 THEN
DBMS_OUTPUT.PUT_LINE('SECOND CLASS! '||PERCENT);
ELSIF PERCENT>40 THEN
DBMS_OUTPUT.PUT_LINE('PASSED '||PERCENT);
ELSE
DBMS_OUTPUT.PUT_LINE('FAILED!!!!!!! '||PERCENT);
END IF;
END;
/