-- SWITCH CASE IN PLSQL
-- CREATING DEMO EMP2 TABLE
CREATE TABLE EMP2(EID NUMBER(3),ENAME VARCHAR2(50),
JOB VARCHAR2(30) CHECK(JOB IN('CLERK','MANAGER','HR','ANALYST','SALESMAN')),
SALARY NUMBER(10));
-- INSERTING VALUES IN EMP2 TABLE
INSERT INTO EMP2 VALUES(101,'MUKESH','SALESMAN',10000);
INSERT INTO EMP2 VALUES(102,'RAMESH','CLERK',12500);
INSERT INTO EMP2 VALUES(103,'GANESH','MANAGER',30000);
INSERT INTO EMP2 VALUES(104,'MAHESH','ANALYST',25000);
INSERT INTO EMP2 VALUES(105,'DIKESH','HR',35000);

-- INREASING SALARY ACCORDING TO JOB TITLE TAKEN FROM USER
DECLARE
EJOB EMP2.JOB%TYPE;
BEGIN
EJOB:='&JOB';
CASE EJOB
WHEN 'CLERK' THEN
UPDATE EMP2 SET SALARY=SALARY+SALARY*0.05 WHERE JOB=EJOB;
WHEN 'MANAGER' THEN
UPDATE EMP2 SET SALARY=SALARY+SALARY*0.075 WHERE JOB=EJOB;
WHEN 'HR' THEN
UPDATE EMP2 SET SALARY=SALARY+SALARY*0.025 WHERE JOB=EJOB;
ELSE
UPDATE EMP2 SET SALARY=SALARY+SALARY*0.1 WHERE JOB=EJOB;
END CASE;
END;
/