DECLARE
USER VARCHAR(20);
BEGIN
USER:='&USE';
CASE USER
WHEN 'SYS' THEN 
DBMS_OUTPUT.PUT_LINE('OWNER IS SYS!');
WHEN 'SYSTEM' THEN
DBMS_OUTPUT.PUT_LINE('THE OWNER IS SYSTEM!');
WHEN 'HR' THEN
DBMS_OUTPUT.PUT_LINE('THE OWNER IS HR!');
WHEN 'SCOTT' THEN
DBMS_OUTPUT.PUT_LINE('THE OWNER IS SCOTT!');
ELSE
DBMS_OUTPUT.PUT_LINE('INVALID CHOICE!!');
END CASE;
END;
/