-- 26TH OCTOBER 2023 --
-- PL/SQL TRIGGER --

-- DEMO TABLE 'MOVIE' FOR TRIGGER --

CREATE TABLE MOVIE(MID NUMBER(10),MNAME VARCHAR2(50));

-- INSERTING VALUES --

INSERT INTO MOVIE VALUES(101,'SHOLAY');
INSERT INTO MOVIE VALUES(102,'KAITHI');

-- CREATING TRIGGER --

CREATE OR REPLACE TRIGGER T1
BEFORE INSERT ON MOVIE
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('MOVIE ID: '||:NEW.MID||CHR(10)||'MOVIE NAME:'||:NEW.MNAME);
END;
/

-- CREATING TRIGGER --
-- REPLACING `BEFORE` WITH AFTER --

CREATE OR REPLACE TRIGGER T1
AFTER INSERT ON MOVIE
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('MOVIE ID: '||:NEW.MID||CHR(10)||'MOVIE NAME:'||:NEW.MNAME);
END;
/

-- CREATING TRIGGER --
-- TRIGGER FOR `BEFORE` UPDATE --

CREATE OR REPLACE TRIGGER T1
BEFORE UPDATE ON MOVIE
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('MOVIE ID: '||:NEW.MID||CHR(10)||'MOVIE NAME:'||:NEW.MNAME);
END;
/

-- CREATING TRIGGER --
-- TRIGGER FOR `AFTER` DELETE --

CREATE OR REPLACE TRIGGER T1
AFTER DELETE ON MOVIE
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('MOVIE ID: '||:OLD.MID||CHR(10)||'MOVIE NAME:'||:OLD.MNAME);
END;
/