-- 26TH OCTOBER 2023 --
-- TRIGGER EXCERCISE --

-- DEMO TABLE STUU
CREATE TABLE STUU(SID NUMBER(10),SNAME VARCHAR2(50));

INSERT INTO STUU VALUES(101,'ELVISH BHAIII');

-- 1.CREATE A TRIGGER ON THE STUDENT TABLE WHICH FIRES WHEN A NEW STUDENT IS ADDED.

CREATE OR REPLACE TRIGGER T2
AFTER INSERT ON STUU
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE(:NEW.SID||CHR(9)||:NEW.SNAME);
-- DBMS_OUTPUT.PUT_LINE(:OLD.SID||CHR(9)||:OLD.SNAME);
END;
/

-- 2.CREATE A TRIGGER ON THE STUDENT TABLE WHICH FIRES WHEN A NEW STUDENT IS UPDATED.

CREATE OR REPLACE TRIGGER T3
AFTER UPDATE ON STUU
FOR EACH ROW
BEGIN
DBMS_OUTPUT.PUT_LINE('NEW VALUES'||:NEW.SID||CHR(9)||:NEW.SNAME);
DBMS_OUTPUT.PUT_LINE('OLD VALUES'||:OLD.SID||CHR(9)||:OLD.SNAME);
END;
/

-- 3.CREATE A TRIGGER ON THE STUDENT TABLE WHICH FIRES WHEN A NEW STUDENT IS DLELTED.

CREATE OR REPLACE TRIGGER T4
AFTER DELETE ON STUU
FOR EACH ROW
BEGIN
-- DBMS_OUTPUT.PUT_LINE(:NEW.SID||CHR(9)||:NEW.SNAME);
DBMS_OUTPUT.PUT_LINE('DELETED VALUES:   '||:OLD.SID||CHR(9)||:OLD.SNAME);
END;
/

-- 4.CREATE A TRIGGER ON THE STUDENT TABLE WHERE TRIGGER SHOULD BE FIRED WHEN THE OLD STUDENT IS DELETED FROM STUDENT TABLE AND ADDED IN NEW STUDENT TABLE.

-- CREATING BACKUP TABLE --------------------------------------|
CREATE TABLE STUU2(SID NUMBER(10),SNAME VARCHAR2(50));    --|
														  --|
CREATE OR REPLACE TRIGGER T5							  --|
AFTER DELETE ON STUU									  --|
FOR EACH ROW											  --|
BEGIN													  --|
INSERT INTO STUU2 VALUES(:OLD.SID,:OLD.SNAME);			--<<-|
DBMS_OUTPUT.PUT_LINE('ROW DELETED AND INSERTED IN STUU2 TABLE');
END;
/
