-- 31st OCTOBER 2023
-- TRIGGER EXCERCISE

CREATE TABLE AUDIT_MOVIE(MOVIE_ID VARCHAR2(5),MOVIE_NAME VARCHAR2(50),RELEASE_DATE DATE);

-- CREATE TABLE MOVIE_LOG(MID VARCHAR2(5),MNAME VARCHAR2(50),LOG_DATE DATE DEFAULT SYSDATE);

CREATE TABLE MOVIE_LOG(MOVIE_ID VARCHAR2(5),MOVIE_NAME VARCHAR2(50),LOG_DATE DATE DEFAULT SYSDATE);

INSERT INTO AUDIT_MOVIE VALUES('M101','DHAMAAL','10-OCT-10');
INSERT INTO AUDIT_MOVIE VALUES('M102','DOUBLE DHAMAAL','12-OCT-12');
INSERT INTO AUDIT_MOVIE VALUES('M103','TOTAL DHAMAAL','14-OCT-20');

CREATE OR REPLACE TRIGGER MOVIE101
AFTER INSERT ON AUDIT_MOVIE
FOR EACH ROW
BEGIN
INSERT INTO MOVIE_LOG(MOVIE_ID,MOVIE_NAME)VALUES(:NEW.MOVIE_ID,:NEW.MOVIE_NAME);
DBMS_OUTPUT.PUT_LINE('MOVIE ADDED TO LOG!!');
END;
/

CREATE OR REPLACE TRIGGER CHK_MOVIE_NAME
BEFORE INSERT ON AUDIT_MOVIE
FOR EACH ROW
WHEN (NEW.MOVIE_NAME NOT LIKE 'P%')
BEGIN
RAISE_APPLICATION_ERROR(-20001,'MOVIE NAME MUST START WITH `P`');
END;
/

CREATE TABLE STUU(SID NUMBER(5),SNAME VARCHAR2(50),AGE NUMBER(3));

INSERT INTO STUU VALUES(101,'ALMAS',19);
INSERT INTO STUU VALUES(102,'NIHAR',19);
INSERT INTO STUU VALUES(103,'HARSH',20);

CREATE OR REPLACE TRIGGER CHK_AGE
BEFORE INSERT ON STUU
FOR EACH ROW
WHEN (NEW.AGE NOT BETWEEN 18 AND 25)
BEGIN
RAISE_APPLICATION_ERROR(-20001,'AGE MUST BE BETWEEEN 18 AND 25!!!');
END;
/

CREATE TABLE E_M_P(EID NUMBER(10),ENAME VARCHAR2(50),SALARY NUMBER(10));

INSERT INTO E_M_P VALUES(101,'KRISH',20000);
INSERT INTO E_M_P VALUES(102,'VIKAS',25000);
INSERT INTO E_M_P VALUES(103,'ADITYA',60000);

CREATE OR REPLACE TRIGGER CHK_SAL
BEFORE INSERT ON E_M_P
FOR EACH ROW
WHEN (NEW.SALARY NOT BETWEEN 30000 AND 100000)
BEGIN
RAISE_APPLICATION_ERROR(-20001,'SALARY MUST BE BETWEEEN 30K AND 100K!!!');
END;
/
-- PARAMETERISED CURSOR EXCERCISE --
DECLARE
SNAME SAILOR.SNAME%TYPE;
SID SAILOR.SID%TYPE;
RATING SAILOR.RATING%TYPE;
RESDATE DATE;
CURSOR CC11('&RESDATE' IN DATE) IS SELECT SAILOR.SID,SAILOR.SNAME,SAILOR.RATING INTO SID,SNAME,RATING FROM SAILOR,RESERVE WHERE RESERVE.RDATE > '10-NOV-10';
BEGIN
END;
/

SELECT UNIQUE SAILOR.SID,SAILOR.SNAME,SAILOR.RATING FROM SAILOR,RESERVE WHERE SAILOR.SID = RESERVE.SID AND RESERVE.RDATE > '11-JUL-23'; 