-- 30TH OCTOBER 2023  TRIGGER LAST EXCERCISE --
-- FOR QUESTIONS REFER TO 'TRIGGER_EXAMPLES' FILE IN PL/SQL FOLDER IN MY Z DRIVE......
-- CREATING TABLES
CREATE TABLE ORDER_TAB(ORDER_NO NUMBER(10) PRIMARY KEY,CUST_CD VARCHAR2(50),STATUS VARCHAR2(10));

CREATE TABLE ORDER_DETAIL(ORDER_NO NUMBER(10) REFERENCES ORDER_TAB(ORDER_NO),PRODUCT_CD NUMBER(10) REFERENCES PRODUCT_MASTER(PRODUCT_CD),QUANTITY NUMBER(10));

CREATE TABLE PRODUCT_MASTER(PRODUCT_CD NUMBER(10) PRIMARY KEY,PRODUCT_NAME VARCHAR2(50),STOCK_QTY NUMBER(10),BOOKED_QTY NUMBER(10));

INSERT INTO ORDER_TAB VALUES(1,'C1','P');
INSERT INTO ORDER_TAB VALUES(2,'C2','P');

INSERT INTO PRODUCT_MASTER VALUES(101,'PENDRIVES 128GB',10000,1000);
INSERT INTO PRODUCT_MASTER VALUES(102,'INTEL I5 6600K',5000,500);
INSERT INTO PRODUCT_MASTER VALUES(103,'GE-FORCE GTX 1660',1000,100);

INSERT INTO ORDER_DETAIL VALUES(1,101,100);
INSERT INTO ORDER_DETAIL VALUES(1,102,50);
INSERT INTO ORDER_DETAIL VALUES(2,103,10);

-- TRIGGER
CREATE OR REPLACE TRIGGER TR1
AFTER DELETE ON ORDER_DETAIL
FOR EACH ROW
BEGIN
UPDATE PRODUCT_MASTER
SET STOCK_QTY = STOCK_QTY + :OLD.QUANTITY
WHERE PRODUCT_CD = :OLD.PRODUCT_CD;
DBMS_OUTPUT.PUT_LINE('ROW DELETED FROM ORDER DETAIL AND STOCKS UPDATED!!');
END;
/

-- TRIGGER2
CREATE OR REPLACE TRIGGER TR2
AFTER UPDATE OR DELETE ON ORDER_DETAIL
FOR EACH ROW
BEGIN
UPDATE PRODUCT_MASTER
SET STOCK_QTY = STOCK_QTY + :NEW.QUANTITY
WHERE PRODUCT_CD = :OLD.PRODUCT_CD;
DBMS_OUTPUT.PUT_LINE('ROW UPDATED FROM ORDER DETAIL AND STOCKS UPDATED TOO!!');
END;
/

-- 5. WRITE A PL/SQL BLOCK FOR BEFORE UPDATE OF COLUMN 'PROD_CD' TRIGGER ON 'ORD_DTL'. THE COLUMN  'BOOKED_QTY' IN 'PROD_MST' SHOULD BE INCREASED OR DECREASED ACCORDINGLY.

CREATE OR REPLACE TRIGGER TR3
BEFORE UPDATE ON ORDER_DETAIL
FOR EACH ROW
BEGIN
UPDATE PRODUCT_MASTER -- 
SET BOOKED_QTY = BOOKED_QTY - :OLD.QUANTITY + :NEW.QUANTITY
WHERE PRODUCT_CD= :OLD.PRODUCT_CD;
END;
/

--NO 2

CREATE TABLE ITEM_RECEIVED(ITEM_CD NUMBER(10) REFERENCES ITEM_STOCK(ITEM_CD),RECIEVE_DATE DATE ,REC_QTY NUMBER(10));

CREATE TABLE ITEM_STOCK(ITEM_CD NUMBER(10) PRIMARY KEY,ORDER_DATE DATE,OPEN_STOCK NUMBER(10), CLOSE_STOCK NUMBER(10));

INSERT INTO ITEM_RECIEVED VALUES(101,'10-OCT-2023',5);
INSERT INTO ITEM_RECIEVED VALUES(102,'5-OCT-2023',10);

INSERT INTO ITEM_STOCK VALUES(101,'5-OCT-2023',500,NULL);
INSERT INTO ITEM_STOCK VALUES(102,'4-OCT-2023',500,NULL);

-- TRIGGER 1

CREATE OR REPLACE TRIGGER IT1
AFTER UPDATE OR DELETE ON ITEM_RECIEVED
FOR EACH ROW
BEGIN
UPDATE ITEM_STOCK SET CLOSE_STOCK = OPEN_STOCK - :NEW.REC_QTY WHERE ITEM_CD = :OLD.ITEM_CD;
END;
/

-- TRIGGER 2

CREATE OR REPLACE TRIGGER IT2
AFTER INSERT ON ITEM_RECIEVED
FOR EACH ROW
BEGIN
UPDATE ITEM_STOCK SET CLOSE_STOCK = OPEN_STOCK - :NEW.REC_QTY WHERE ITEM_CD = :NEW.ITEM_CD;
END;
/

INSERT INTO ITEM_RECIEVED VALUES(102,'28-FEB-2023',10);

-- TRIGGER 3 FROM EXCERCISE --

-- CREATING BACKUP TABLE

CREATE TABLE ITEM_LOG(ITEM_CD NUMBER(10),RECIEVE_DATE DATE,REC_QTY NUMBER(10));

-- TRIGGER THAT BACKS UP VALUES FROM ITEM_RECIEVED INTO ITEM_LOG --

CREATE OR REPLACE TRIGGER IT3
AFTER UPDATE OR DELETE ON ITEM_RECIEVED
FOR EACH ROW
BEGIN
INSERT INTO ITEM_LOG VALUES(:OLD.ITEM_CD,:OLD.RECIEVE_DATE,:OLD.REC_QTY);
END;
/

-- DEMO QUERY TO CHECK TRIGGER --
DELETE ITEM_RECIEVED WHERE ITEM_CD=101;
