-- 28TH OCTOBER 2023 --
-- TRIGGER EXCERCISE --

-- DEMO EMPPP TABLE --

CREATE TABLE EMPPP(EID NUMBER(10),ENAME VARCHAR2(50));
CREATE TABLE BAK_EMPPP(EID NUMBER(10),ENAME VARCHAR2(50));

-- INSERTING INTO EMPPP --
INSERT INTO EMPPP VALUES(101,'ELVISH BHAIII');
INSERT INTO EMPPP VALUES(102,'KRISH BHAIII');
INSERT INTO EMPPP VALUES(103,'VIKAS');
INSERT INTO EMPPP VALUES(104,'BURHAN');

INSERT INTO BAK_EMPPP VALUES(101,'ELVISH BHAIII');
INSERT INTO BAK_EMPPP VALUES(102,'KRISH BHAIII');
INSERT INTO BAK_EMPPP VALUES(103,'VIKAS');
INSERT INTO BAK_EMPPP VALUES(104,'BURHAN');

-- TRIGGER FOR UPDATE ON EMPPP --

CREATE OR REPLACE TRIGGER TT1
AFTER UPDATE OF EID ON EMPPP
FOR EACH ROW
BEGIN
UPDATE BAK_EMPPP SET EID=:NEW.EID WHERE EID=:OLD.EID;
DBMS_OUTPUT.PUT_LINE('ROW UPDATED IN BACKUP TABLE');
END;
/

-- DEMO TABLE FOR OTHER EXCERCISE --

CREATE TABLE EEMMPP(EID NUMBER(10),ENAME VARCHAR2(50),SALARY NUMBER(10),COMM NUMBER(10));

INSERT INTO EEMMPP VALUES(111,'DHRUV',10000,NULL);
INSERT INTO EEMMPP VALUES(112,'VIKAS',12000,NULL);
INSERT INTO EEMMPP VALUES(113,'NIHAR',14000,NULL);

CREATE OR REPLACE TRIGGER TT2
BEFORE INSERT ON EEMMPP
FOR EACH ROW
BEGIN
IF :NEW.EID = 30 THEN
:NEW.COMM := :NEW.SALARY * 0.5;
END IF;
END;
/

-- TRIGGER 3 --

CREATE OR REPLACE TRIGGER TT3
BEFORE INSERT OR UPDATE OR DELETE ON EEMMPP
FOR EACH ROW
DECLARE SAL_DIFF NUMBER;
BEGIN
WHEN (SALARY>0) THEN
SAL_DIFF := :NEW.SALARY - :OLD.SALARY;
DBMS_OUTPUT.PUT_LINE('OLD SALARY: '||:OLD.SALARY);
DBMS_OUTPUT.PUT_LINE('NEW SALARY: '||:NEW.SALARY);
DBMS_OUTPUT.PUT_LINE('DIFF BETWEEN OLD AND NEW SALARY: '||SAL_DIFF);
END;
/
